CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE tbl_app_health (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NULL,
    value text NULL,
    iscr boolean NOT NULL,
    CONSTRAINT "PK_tbl_app_health" PRIMARY KEY (id)
);

CREATE TABLE tbl_appvariable (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nature text NULL,
    name text NULL,
    value numeric(19,4) NULL,
    isactive boolean NULL,
    isdefault boolean NULL,
    iseditable boolean NULL,
    isdeleted boolean NULL,
    CONSTRAINT "PK_tbl_appvariable" PRIMARY KEY (id)
);

CREATE TABLE tbl_enterprise (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NULL,
    enterpriseguid uuid NOT NULL,
    description text NULL,
    email text NULL,
    phone text NULL,
    mobileone text NULL,
    mobiletwo text NULL,
    matriculefiscal text NULL,
    devise text NULL,
    nameresponsable text NULL,
    surnameresponsable text NULL,
    positionresponsable text NULL,
    siegeaddress text NULL,
    commercialregister text NULL,
    capital text NULL,
    issalingwood boolean NULL,
    CONSTRAINT "PK_tbl_enterprise" PRIMARY KEY (id)
);

CREATE TABLE tbl_pending_notification (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    content text NOT NULL,
    targetgroup character varying(100) NOT NULL,
    status integer NOT NULL,
    retry_count integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    last_attempt_at timestamp without time zone NULL,
    delivered_at timestamp without time zone NULL,
    error_message character varying(500) NULL,
    CONSTRAINT "PK_tbl_pending_notification" PRIMARY KEY (id)
);

CREATE TABLE tbl_person (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guid uuid NOT NULL,
    firstname text NULL,
    lastname text NULL,
    fullname text NULL,
    birthdate timestamp without time zone NULL,
    cin text NULL,
    idcnss text NULL,
    idrole integer NOT NULL,
    address text NULL,
    birthtown text NULL,
    bankname text NULL,
    bankaccount text NULL,
    phonenumber text NULL,
    isdeleted boolean NOT NULL,
    isappuser boolean NOT NULL,
    hiredate timestamp without time zone NULL,
    firedate timestamp without time zone NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    idappuser integer NULL,
    CONSTRAINT "PK_tbl_person" PRIMARY KEY (id)
);

CREATE TABLE tbl_sell_history (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    pricevalue double precision NOT NULL,
    description text NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    idarticle integer NOT NULL,
    idappuser integer NOT NULL,
    CONSTRAINT "PK_tbl_sell_history" PRIMARY KEY (id)
);

CREATE TABLE tbl_vehicle (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    serialnumber text NULL,
    brand text NULL,
    insurancedate timestamp without time zone NULL,
    technicalvisitdate timestamp without time zone NULL,
    mileage text NULL,
    draining text NULL,
    drainingdate timestamp without time zone NULL,
    CONSTRAINT "PK_tbl_vehicle" PRIMARY KEY (id)
);

CREATE TABLE tbl_sales_sites (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    isforsale boolean NOT NULL,
    gouvernorate text NULL,
    address text NULL,
    codepost text NULL,
    isdeleted boolean NOT NULL,
    enterpriseid integer NOT NULL,
    CONSTRAINT "PK_tbl_sales_sites" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_sales_sites_tbl_enterprise_enterpriseid" FOREIGN KEY (enterpriseid) REFERENCES tbl_enterprise (id) ON DELETE CASCADE
);

CREATE TABLE tbl_transporter (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    firstname text NULL,
    lastname text NULL,
    fullname text NULL,
    vehicleid integer NULL,
    CONSTRAINT "PK_tbl_transporter" PRIMARY KEY (id),
    CONSTRAINT fk_tbl_transporter_tbl_vehicle FOREIGN KEY (vehicleid) REFERENCES tbl_vehicle (id) ON DELETE CASCADE
);

CREATE TABLE tbl_app_user (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    login text NULL,
    email text NULL,
    isactive boolean NOT NULL,
    passwordhash bytea NULL,
    passwordsalt bytea NULL,
    idperson integer NOT NULL,
    enterpriseid integer NULL,
    idsalessite integer NULL,
    CONSTRAINT "PK_tbl_app_user" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_app_user_tbl_enterprise_enterpriseid" FOREIGN KEY (enterpriseid) REFERENCES tbl_enterprise (id),
    CONSTRAINT "FK_tbl_app_user_tbl_person_idperson" FOREIGN KEY (idperson) REFERENCES tbl_person (id) ON DELETE SET NULL,
    CONSTRAINT "FK_tbl_app_user_tbl_sales_sites_idsalessite" FOREIGN KEY (idsalessite) REFERENCES tbl_sales_sites (id)
);

CREATE TABLE "HoldingTax" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "TaxPercentage" double precision NOT NULL,
    "TaxValue" double precision NOT NULL,
    "isSigned" boolean NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    "UpdateDate" timestamp without time zone NOT NULL,
    "NewAmountDocValue" double precision NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UpdatedById" integer NOT NULL,
    "AppUsersId" integer NULL,
    CONSTRAINT "PK_HoldingTax" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HoldingTax_tbl_app_user_AppUsersId" FOREIGN KEY ("AppUsersId") REFERENCES tbl_app_user (id)
);

CREATE TABLE tbl_bank (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    reference text NULL,
    description text NULL,
    logo text NULL,
    agency text NULL,
    rib text NULL,
    iban text NULL,
    creationdate timestamp without time zone NOT NULL,
    updatedate timestamp without time zone NOT NULL,
    isdeleted boolean NULL,
    idappuser integer NULL,
    CONSTRAINT "PK_tbl_bank" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_bank_tbl_app_user_idappuser" FOREIGN KEY (idappuser) REFERENCES tbl_app_user (id)
);

CREATE TABLE tbl_counter_part (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guid uuid NULL,
    type integer NOT NULL,
    prefix text NULL,
    name text NULL,
    description text NULL,
    firstname text NULL,
    lastname text NULL,
    identitycardnumber text NULL,
    email text NULL,
    taxregistrationnumber text NULL,
    patentecode text NULL,
    address text NULL,
    gouvernorate text NULL,
    maximumdiscount double precision NULL,
    openingbalance numeric NULL,
    maximumsalesbar double precision NULL,
    notes text NULL,
    phonenumberone text NULL,
    phonenumbertwo text NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    jobtitle text NULL,
    bankname text NULL,
    bankaccountnumber text NULL,
    isactive boolean NULL,
    isdeleted boolean NULL,
    updatedby integer NOT NULL,
    transporterid integer NULL,
    CONSTRAINT "PK_tbl_counter_part" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_counter_part_tbl_app_user_updatedby" FOREIGN KEY (updatedby) REFERENCES tbl_app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_tbl_counter_part_tbl_transporter FOREIGN KEY (transporterid) REFERENCES tbl_transporter (id) ON DELETE SET NULL
);

CREATE TABLE tbl_parent (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    reference text NULL,
    description text NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    idappuser integer NULL,
    CONSTRAINT "PK_tbl_parent" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_parent_tbl_app_user_idappuser" FOREIGN KEY (idappuser) REFERENCES tbl_app_user (id) ON DELETE SET NULL
);

CREATE TABLE tbl_provider (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    prefix text NULL,
    name text NULL,
    description text NULL,
    representedbyname text NULL,
    representedbysurname text NULL,
    representedbyfullname text NULL,
    address text NULL,
    email text NULL,
    category text NULL,
    taxregistrationnumber text NULL,
    phonenumberone text NULL,
    phonenumbertwo text NULL,
    bankname text NULL,
    bankaccountnumber text NULL,
    isdeleted boolean NOT NULL,
    isactive boolean NOT NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    idappuser integer NOT NULL,
    CONSTRAINT "PK_tbl_provider" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_provider_tbl_app_user_idappuser" FOREIGN KEY (idappuser) REFERENCES tbl_app_user (id) ON DELETE CASCADE
);

CREATE TABLE tbl_account_ledger (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    counterpartid integer NOT NULL,
    transactiondate timestamp without time zone NOT NULL,
    type text NOT NULL,
    relatedid integer NULL,
    debit numeric NOT NULL,
    credit numeric NOT NULL,
    description text NULL,
    createdat timestamp without time zone NOT NULL,
    updatedat timestamp without time zone NOT NULL,
    CONSTRAINT "PK_tbl_account_ledger" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_account_ledger_tbl_counter_part_counterpartid" FOREIGN KEY (counterpartid) REFERENCES tbl_counter_part (id) ON DELETE RESTRICT
);

CREATE TABLE tbl_document (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    type integer NULL,
    stocktransactiontype integer NULL,
    docnumber text NULL,
    description text NULL,
    supplierreference text NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isinvoiced boolean NOT NULL,
    withholdingtax boolean NOT NULL,
    totalcostpriceht numeric(19,4) NOT NULL,
    totalcostpricettc numeric(19,4) NOT NULL,
    totalcosttva numeric(19,4) NOT NULL,
    totalcostdiscount numeric(19,4) NOT NULL,
    holdingtaxid integer NULL,
    taxeid integer NULL,
    updatedbyid integer NULL,
    counterpartid integer NOT NULL,
    isdeleted boolean NOT NULL DEFAULT FALSE,
    salessiteid integer NOT NULL,
    docstatus integer NOT NULL,
    billingstatus integer NOT NULL,
    isservice boolean NOT NULL,
    CONSTRAINT "PK_tbl_document" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_document_tbl_appvariable_taxeid" FOREIGN KEY (taxeid) REFERENCES tbl_appvariable (id),
    CONSTRAINT "FK_tbl_document_tbl_counter_part_counterpartid" FOREIGN KEY (counterpartid) REFERENCES tbl_counter_part (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_document_tbl_sales_sites_salessiteid" FOREIGN KEY (salessiteid) REFERENCES tbl_sales_sites (id) ON DELETE CASCADE,
    CONSTRAINT fk_tbl_document_tbl_app_user FOREIGN KEY (updatedbyid) REFERENCES tbl_app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tbl_document_tbl_holding_tax FOREIGN KEY (holdingtaxid) REFERENCES "HoldingTax" ("Id") ON DELETE SET NULL
);

CREATE TABLE tbl_first_child (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    reference text NULL,
    description text NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    idappuser integer NULL,
    idparent integer NULL,
    CONSTRAINT "PK_tbl_first_child" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_first_child_tbl_app_user_idappuser" FOREIGN KEY (idappuser) REFERENCES tbl_app_user (id) ON DELETE SET NULL,
    CONSTRAINT "FK_tbl_first_child_tbl_parent_idparent" FOREIGN KEY (idparent) REFERENCES tbl_parent (id)
);

CREATE TABLE tbl_document_document_relationship (
    parent_document_id integer NOT NULL,
    child_document_id integer NOT NULL,
    CONSTRAINT "PK_tbl_document_document_relationship" PRIMARY KEY (parent_document_id, child_document_id),
    CONSTRAINT "FK_tbl_document_document_relationship_tbl_document_child_docum~" FOREIGN KEY (child_document_id) REFERENCES tbl_document (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_document_document_relationship_tbl_document_parent_docu~" FOREIGN KEY (parent_document_id) REFERENCES tbl_document (id) ON DELETE RESTRICT
);

CREATE TABLE tbl_payments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    documentid integer NOT NULL,
    customerid integer NOT NULL,
    paymentdate timestamp without time zone NULL,
    amount numeric NULL,
    paymentmethod text NULL,
    reference text NULL,
    notes text NULL,
    createdat timestamp without time zone NULL,
    createdby text NULL,
    updatedat timestamp without time zone NULL,
    updatedbyid integer NULL,
    isdeleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_tbl_payments" PRIMARY KEY (id),
    CONSTRAINT fk_tbl_payments_tbl_app_user FOREIGN KEY (updatedbyid) REFERENCES tbl_app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tbl_payments_tbl_counter_part FOREIGN KEY (customerid) REFERENCES tbl_counter_part (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tbl_payments_tbl_document FOREIGN KEY (documentid) REFERENCES tbl_document (id) ON DELETE RESTRICT
);

CREATE TABLE tbl_stock_transfer (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    exitdocumentid integer NOT NULL,
    receiptdocumentid integer NOT NULL,
    transferdate timestamp without time zone NOT NULL,
    reference text NULL,
    notes text NULL,
    transporterid integer NULL,
    creationdate timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    createdbyid integer NOT NULL,
    status integer NOT NULL,
    confirmedbyid integer NULL,
    confirmationdate timestamp without time zone NULL,
    rejectionreason text NULL,
    confirmationcode character varying(10) NULL,
    CONSTRAINT "PK_tbl_stock_transfer" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_stock_transfer_tbl_app_user_createdbyid" FOREIGN KEY (createdbyid) REFERENCES tbl_app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_stock_transfer_tbl_document_exitdocumentid" FOREIGN KEY (exitdocumentid) REFERENCES tbl_document (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_stock_transfer_tbl_document_receiptdocumentid" FOREIGN KEY (receiptdocumentid) REFERENCES tbl_document (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_stock_transfer_tbl_transporter_transporterid" FOREIGN KEY (transporterid) REFERENCES tbl_transporter (id) ON DELETE SET NULL
);

CREATE TABLE tbl_article (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    reference text NULL,
    description text NULL,
    iswood boolean NOT NULL,
    creationdate timestamp without time zone NOT NULL,
    updatedate timestamp without time zone NOT NULL,
    isdeleted boolean NOT NULL,
    minquantity double precision NULL,
    unit text NULL,
    sellprice_ht double precision NULL,
    sellprice_ttc double precision NULL,
    lastpurchaseprice_ttc double precision NOT NULL,
    profitmarginpercentage double precision NULL,
    lengths text NULL,
    idsellhistory integer NULL,
    idtva integer NOT NULL,
    idcategory integer NOT NULL,
    idsubcategory integer NOT NULL,
    idappuser integer NOT NULL,
    idthickness integer NULL,
    idwidth integer NULL,
    CONSTRAINT "PK_tbl_article" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_article_tbl_app_user_idappuser" FOREIGN KEY (idappuser) REFERENCES tbl_app_user (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_article_tbl_appvariable_idthickness" FOREIGN KEY (idthickness) REFERENCES tbl_appvariable (id),
    CONSTRAINT "FK_tbl_article_tbl_appvariable_idtva" FOREIGN KEY (idtva) REFERENCES tbl_appvariable (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_article_tbl_appvariable_idwidth" FOREIGN KEY (idwidth) REFERENCES tbl_appvariable (id),
    CONSTRAINT "FK_tbl_article_tbl_first_child_idsubcategory" FOREIGN KEY (idsubcategory) REFERENCES tbl_first_child (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_article_tbl_parent_idcategory" FOREIGN KEY (idcategory) REFERENCES tbl_parent (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_article_tbl_sell_history_idsellhistory" FOREIGN KEY (idsellhistory) REFERENCES tbl_sell_history (id)
);

CREATE TABLE tbl_second_child (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    reference text NULL,
    description text NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    idappuser integer NULL,
    "AppUserId" integer NULL,
    "IdFirstChild" integer NULL,
    CONSTRAINT "PK_tbl_second_child" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_second_child_tbl_app_user_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES tbl_app_user (id),
    CONSTRAINT "FK_tbl_second_child_tbl_first_child_IdFirstChild" FOREIGN KEY ("IdFirstChild") REFERENCES tbl_first_child (id)
);

CREATE TABLE tbl_merchandise (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    packagereference text NULL,
    description text NULL,
    isinvoicible boolean NOT NULL,
    allownegativstock boolean NOT NULL,
    ismergedwith boolean NOT NULL,
    idmergedmerchandise integer NULL,
    isdeleted boolean NOT NULL,
    articleid integer NOT NULL,
    updatedbyid integer NOT NULL,
    CONSTRAINT "PK_tbl_merchandise" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_merchandise_tbl_app_user_updatedbyid" FOREIGN KEY (updatedbyid) REFERENCES tbl_app_user (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_merchandise_tbl_article_articleid" FOREIGN KEY (articleid) REFERENCES tbl_article (id) ON DELETE RESTRICT
);

CREATE TABLE "DocumentMerchandise" (
    "DocumentsId" integer NOT NULL,
    "MerchandisesId" integer NOT NULL,
    CONSTRAINT "PK_DocumentMerchandise" PRIMARY KEY ("DocumentsId", "MerchandisesId"),
    CONSTRAINT "FK_DocumentMerchandise_tbl_document_DocumentsId" FOREIGN KEY ("DocumentsId") REFERENCES tbl_document (id) ON DELETE CASCADE,
    CONSTRAINT "FK_DocumentMerchandise_tbl_merchandise_MerchandisesId" FOREIGN KEY ("MerchandisesId") REFERENCES tbl_merchandise (id) ON DELETE CASCADE
);

CREATE TABLE tbl_document_merchandise (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    creation_date timestamp without time zone NULL,
    update_date timestamp without time zone NULL,
    quantity numeric(19,4) NOT NULL,
    unitprice_ht numeric(19,4) NOT NULL,
    cost_ht numeric(19,4) NOT NULL,
    discount_percentage numeric(5,2) NOT NULL,
    cost_net_ht numeric(19,4) NOT NULL,
    cost_discount_value numeric(19,4) NOT NULL,
    tva_value numeric(19,4) NOT NULL,
    cost_ttc numeric(19,4) NOT NULL,
    documentid integer NOT NULL,
    merchandiseid integer NOT NULL,
    CONSTRAINT "PK_tbl_document_merchandise" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_document_merchandise_tbl_document_documentid" FOREIGN KEY (documentid) REFERENCES tbl_document (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_document_merchandise_tbl_merchandise_merchandiseid" FOREIGN KEY (merchandiseid) REFERENCES tbl_merchandise (id) ON DELETE CASCADE
);

CREATE TABLE tbl_stock (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    quantity double precision NOT NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    type integer NOT NULL,
    idmerchandise integer NOT NULL,
    idsite integer NOT NULL,
    updatedbyid integer NOT NULL,
    CONSTRAINT "PK_tbl_stock" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_stock_tbl_merchandise_idmerchandise" FOREIGN KEY (idmerchandise) REFERENCES tbl_merchandise (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_stock_tbl_sales_sites_idsite" FOREIGN KEY (idsite) REFERENCES tbl_sales_sites (id) ON DELETE CASCADE,
    CONSTRAINT fk_tbl_stock_tbl_app_user FOREIGN KEY (updatedbyid) REFERENCES tbl_app_user (id) ON DELETE RESTRICT
);

CREATE TABLE tbl_quantity_mouvements (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    lengthids text NULL,
    quantity double precision NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    document_merchandise_id integer NOT NULL,
    CONSTRAINT "PK_tbl_quantity_mouvements" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_quantity_mouvements_tbl_document_merchandise_document_m~" FOREIGN KEY (document_merchandise_id) REFERENCES tbl_document_merchandise (id) ON DELETE CASCADE
);

CREATE TABLE tbl_list_of_lengths (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    numberofpieces integer NOT NULL,
    quantity double precision NOT NULL,
    lengthappvarid integer NULL,
    quantitymouvementid integer NOT NULL,
    CONSTRAINT "PK_tbl_list_of_lengths" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_list_of_lengths_tbl_appvariable_lengthappvarid" FOREIGN KEY (lengthappvarid) REFERENCES tbl_appvariable (id) ON DELETE SET NULL,
    CONSTRAINT "FK_tbl_list_of_lengths_tbl_quantity_mouvements_quantitymouveme~" FOREIGN KEY (quantitymouvementid) REFERENCES tbl_quantity_mouvements (id) ON DELETE CASCADE
);

CREATE INDEX "IX_DocumentMerchandise_MerchandisesId" ON "DocumentMerchandise" ("MerchandisesId");

CREATE INDEX "IX_HoldingTax_AppUsersId" ON "HoldingTax" ("AppUsersId");

CREATE INDEX "IX_tbl_account_ledger_counterpartid" ON tbl_account_ledger (counterpartid);

CREATE UNIQUE INDEX "IX_tbl_app_user_enterpriseid" ON tbl_app_user (enterpriseid);

CREATE INDEX "IX_tbl_app_user_idperson" ON tbl_app_user (idperson);

CREATE UNIQUE INDEX "IX_tbl_app_user_idsalessite" ON tbl_app_user (idsalessite);

CREATE INDEX "IX_tbl_article_idappuser" ON tbl_article (idappuser);

CREATE INDEX "IX_tbl_article_idcategory" ON tbl_article (idcategory);

CREATE INDEX "IX_tbl_article_idsellhistory" ON tbl_article (idsellhistory);

CREATE INDEX "IX_tbl_article_idsubcategory" ON tbl_article (idsubcategory);

CREATE INDEX "IX_tbl_article_idthickness" ON tbl_article (idthickness);

CREATE INDEX "IX_tbl_article_idtva" ON tbl_article (idtva);

CREATE INDEX "IX_tbl_article_idwidth" ON tbl_article (idwidth);

CREATE INDEX "IX_tbl_bank_idappuser" ON tbl_bank (idappuser);

CREATE INDEX "IX_tbl_counter_part_transporterid" ON tbl_counter_part (transporterid);

CREATE INDEX "IX_tbl_counter_part_updatedby" ON tbl_counter_part (updatedby);

CREATE INDEX "IX_tbl_document_counterpartid" ON tbl_document (counterpartid);

CREATE INDEX "IX_tbl_document_holdingtaxid" ON tbl_document (holdingtaxid);

CREATE INDEX "IX_tbl_document_salessiteid" ON tbl_document (salessiteid);

CREATE INDEX "IX_tbl_document_taxeid" ON tbl_document (taxeid);

CREATE INDEX "IX_tbl_document_updatedbyid" ON tbl_document (updatedbyid);

CREATE INDEX "IX_tbl_document_document_relationship_child_document_id" ON tbl_document_document_relationship (child_document_id);

CREATE INDEX "IX_tbl_document_merchandise_documentid" ON tbl_document_merchandise (documentid);

CREATE INDEX "IX_tbl_document_merchandise_merchandiseid" ON tbl_document_merchandise (merchandiseid);

CREATE INDEX "IX_tbl_first_child_idappuser" ON tbl_first_child (idappuser);

CREATE INDEX "IX_tbl_first_child_idparent" ON tbl_first_child (idparent);

CREATE INDEX "IX_tbl_list_of_lengths_lengthappvarid" ON tbl_list_of_lengths (lengthappvarid);

CREATE INDEX "IX_tbl_list_of_lengths_quantitymouvementid" ON tbl_list_of_lengths (quantitymouvementid);

CREATE INDEX "IX_tbl_merchandise_articleid" ON tbl_merchandise (articleid);

CREATE INDEX "IX_tbl_merchandise_updatedbyid" ON tbl_merchandise (updatedbyid);

CREATE INDEX "IX_tbl_parent_idappuser" ON tbl_parent (idappuser);

CREATE INDEX "IX_tbl_payments_customerid" ON tbl_payments (customerid);

CREATE INDEX "IX_tbl_payments_documentid" ON tbl_payments (documentid);

CREATE INDEX "IX_tbl_payments_updatedbyid" ON tbl_payments (updatedbyid);

CREATE INDEX "IX_tbl_pending_notification_targetgroup_status" ON tbl_pending_notification (targetgroup, status);

CREATE INDEX "IX_tbl_provider_idappuser" ON tbl_provider (idappuser);

CREATE UNIQUE INDEX "IX_tbl_quantity_mouvements_document_merchandise_id" ON tbl_quantity_mouvements (document_merchandise_id);

CREATE INDEX "IX_tbl_sales_sites_enterpriseid" ON tbl_sales_sites (enterpriseid);

CREATE INDEX "IX_tbl_second_child_AppUserId" ON tbl_second_child ("AppUserId");

CREATE INDEX "IX_tbl_second_child_IdFirstChild" ON tbl_second_child ("IdFirstChild");

CREATE INDEX "IX_tbl_stock_idmerchandise" ON tbl_stock (idmerchandise);

CREATE INDEX "IX_tbl_stock_idsite" ON tbl_stock (idsite);

CREATE INDEX "IX_tbl_stock_updatedbyid" ON tbl_stock (updatedbyid);

CREATE INDEX "IX_tbl_stock_transfer_createdbyid" ON tbl_stock_transfer (createdbyid);

CREATE INDEX "IX_tbl_stock_transfer_exitdocumentid" ON tbl_stock_transfer (exitdocumentid);

CREATE INDEX "IX_tbl_stock_transfer_receiptdocumentid" ON tbl_stock_transfer (receiptdocumentid);

CREATE INDEX ix_tbl_stock_transfer_reference ON tbl_stock_transfer (reference) WHERE reference IS NOT NULL;

CREATE INDEX ix_tbl_stock_transfer_transferdate ON tbl_stock_transfer (transferdate);

CREATE INDEX "IX_tbl_stock_transfer_transporterid" ON tbl_stock_transfer (transporterid);

CREATE INDEX "IX_tbl_transporter_vehicleid" ON tbl_transporter (vehicleid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310162842_InitialMigration', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_enterprise ADD "AuditRetentionMonths" integer NOT NULL DEFAULT 0;

CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NULL,
    "UserName" text NULL,
    "Action" text NOT NULL,
    "TableName" text NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "KeyValues" text NULL,
    "OldValues" text NULL,
    "NewValues" text NULL,
    "ChangedColumns" text NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413070039_AddAuditTrail', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE "AppNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Message" text NOT NULL,
    "Type" integer NOT NULL,
    "Priority" integer NOT NULL,
    "TargetUserId" integer NULL,
    "TargetRole" character varying(100) NULL,
    "TargetSiteId" integer NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ViewedAt" timestamp without time zone NULL,
    "RelatedEntityId" text NULL,
    "RelatedEntityType" text NULL,
    "EmailRecipient" text NULL,
    "EmailSent" boolean NULL,
    "EmailSentAt" timestamp without time zone NULL,
    CONSTRAINT "PK_AppNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppNotifications_tbl_app_user_TargetUserId" FOREIGN KEY ("TargetUserId") REFERENCES tbl_app_user (id),
    CONSTRAINT "FK_AppNotifications_tbl_sales_sites_TargetSiteId" FOREIGN KEY ("TargetSiteId") REFERENCES tbl_sales_sites (id)
);

CREATE INDEX "IX_AuditLogs_TableName" ON "AuditLogs" ("TableName");

CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");

CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");

CREATE INDEX "IX_AppNotifications_TargetSiteId" ON "AppNotifications" ("TargetSiteId");

CREATE INDEX "IX_AppNotifications_TargetUserId" ON "AppNotifications" ("TargetUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260414134634_AddAppNotifications', '7.0.20');

COMMIT;

START TRANSACTION;


                ALTER TABLE tbl_document_merchandise 
                DROP COLUMN IF EXISTS quantitydelivered;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260414201428_AddQuantityDeliveredToDocumentMerchandise', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "HoldingTax" DROP CONSTRAINT "FK_HoldingTax_tbl_app_user_AppUsersId";

ALTER TABLE "HoldingTax" DROP CONSTRAINT "PK_HoldingTax";

ALTER TABLE "HoldingTax" RENAME TO tbl_holding_tax;

ALTER TABLE tbl_holding_tax RENAME COLUMN "isSigned" TO issigned;

ALTER TABLE tbl_holding_tax RENAME COLUMN "UpdatedById" TO updatedbyid;

ALTER TABLE tbl_holding_tax RENAME COLUMN "UpdateDate" TO updatedate;

ALTER TABLE tbl_holding_tax RENAME COLUMN "TaxValue" TO taxvalue;

ALTER TABLE tbl_holding_tax RENAME COLUMN "TaxPercentage" TO taxpercentage;

ALTER TABLE tbl_holding_tax RENAME COLUMN "NewAmountDocValue" TO newamountdocvalue;

ALTER TABLE tbl_holding_tax RENAME COLUMN "IsDeleted" TO isdeleted;

ALTER TABLE tbl_holding_tax RENAME COLUMN "Description" TO description;

ALTER TABLE tbl_holding_tax RENAME COLUMN "CreationDate" TO creationdate;

ALTER TABLE tbl_holding_tax RENAME COLUMN "AppUsersId" TO appusersid;

ALTER TABLE tbl_holding_tax RENAME COLUMN "Id" TO id;

ALTER INDEX "IX_HoldingTax_AppUsersId" RENAME TO "IX_tbl_holding_tax_appusersid";

ALTER TABLE tbl_document_merchandise ALTER COLUMN "QuantityDelivered" SET DEFAULT 0.0;

ALTER TABLE tbl_holding_tax ALTER COLUMN isdeleted SET DEFAULT FALSE;

ALTER TABLE tbl_holding_tax ADD reference text NULL;

ALTER TABLE tbl_holding_tax ADD CONSTRAINT "PK_tbl_holding_tax" PRIMARY KEY (id);

ALTER TABLE tbl_holding_tax ADD CONSTRAINT "FK_tbl_holding_tax_tbl_app_user_appusersid" FOREIGN KEY (appusersid) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260415131429_FixHoldingTaxMappingFinal', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE tbl_purchase_price_history (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    idarticle integer NOT NULL,
    idcounterpart integer NOT NULL,
    pricevalue double precision NOT NULL,
    transactiondate timestamp without time zone NOT NULL,
    iddocument integer NOT NULL,
    docnumber character varying(50) NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    CONSTRAINT "PK_tbl_purchase_price_history" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_purchase_price_history_tbl_article_idarticle" FOREIGN KEY (idarticle) REFERENCES tbl_article (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_purchase_price_history_tbl_counter_part_idcounterpart" FOREIGN KEY (idcounterpart) REFERENCES tbl_counter_part (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_purchase_price_history_tbl_document_iddocument" FOREIGN KEY (iddocument) REFERENCES tbl_document (id) ON DELETE RESTRICT
);

CREATE TABLE tbl_sales_price_history (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    idarticle integer NOT NULL,
    idcounterpart integer NOT NULL,
    pricevalue double precision NOT NULL,
    transactiondate timestamp without time zone NOT NULL,
    iddocument integer NOT NULL,
    docnumber character varying(50) NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    CONSTRAINT "PK_tbl_sales_price_history" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_sales_price_history_tbl_article_idarticle" FOREIGN KEY (idarticle) REFERENCES tbl_article (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_sales_price_history_tbl_counter_part_idcounterpart" FOREIGN KEY (idcounterpart) REFERENCES tbl_counter_part (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_sales_price_history_tbl_document_iddocument" FOREIGN KEY (iddocument) REFERENCES tbl_document (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_tbl_purchase_price_history_idarticle" ON tbl_purchase_price_history (idarticle);

CREATE INDEX "IX_tbl_purchase_price_history_idcounterpart" ON tbl_purchase_price_history (idcounterpart);

CREATE INDEX "IX_tbl_purchase_price_history_iddocument" ON tbl_purchase_price_history (iddocument);

CREATE INDEX "IX_tbl_sales_price_history_idarticle" ON tbl_sales_price_history (idarticle);

CREATE INDEX "IX_tbl_sales_price_history_idcounterpart" ON tbl_sales_price_history (idcounterpart);

CREATE INDEX "IX_tbl_sales_price_history_iddocument" ON tbl_sales_price_history (iddocument);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419151900_AddTransactionalPriceHistory', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_sales_price_history ADD idupdatedby integer NULL;

ALTER TABLE tbl_purchase_price_history ADD idupdatedby integer NULL;

CREATE INDEX "IX_tbl_sell_history_idappuser" ON tbl_sell_history (idappuser);

CREATE INDEX "IX_tbl_sales_price_history_idupdatedby" ON tbl_sales_price_history (idupdatedby);

CREATE INDEX "IX_tbl_purchase_price_history_idupdatedby" ON tbl_purchase_price_history (idupdatedby);

ALTER TABLE tbl_purchase_price_history ADD CONSTRAINT "FK_tbl_purchase_price_history_tbl_app_user_idupdatedby" FOREIGN KEY (idupdatedby) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

ALTER TABLE tbl_sales_price_history ADD CONSTRAINT "FK_tbl_sales_price_history_tbl_app_user_idupdatedby" FOREIGN KEY (idupdatedby) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

ALTER TABLE tbl_sell_history ADD CONSTRAINT "FK_tbl_sell_history_tbl_app_user_idappuser" FOREIGN KEY (idappuser) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420085615_AddUserAuditToHistory', '7.0.20');

COMMIT;

START TRANSACTION;


                UPDATE tbl_account_ledger
                SET credit = debit, debit = 0
                WHERE type = 'supplierReceipt' 
                  AND (debit > 0 OR debit < 0)
                  AND credit = 0;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429052233_FixSupplierLedgerValues', '7.0.20');

COMMIT;

START TRANSACTION;


                UPDATE tbl_appvariable av
                SET value = sub.calculated_balance
                FROM (
                    SELECT cp.id, (COALESCE(cp.openingbalance, 0) + COALESCE(SUM(al.credit), 0) - COALESCE(SUM(al.debit), 0)) as calculated_balance
                    FROM tbl_counter_part cp
                    LEFT JOIN tbl_account_ledger al ON cp.id = al.counterpartid
                    WHERE cp.type IN (2, 3)
                    GROUP BY cp.id, cp.openingbalance
                ) sub
                WHERE av.nature = 'supplierBalance' 
                  AND (split_part(av.name, '|', 1))::int = sub.id;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429052415_RefreshSupplierBalances', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE approval_configs (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EnterpriseId" integer NOT NULL,
    "ThresholdAmount" numeric(18,3) NULL,
    "ApproverEmails" text NULL,
    "ApproverRoles" text NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_approval_configs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_approval_configs_tbl_enterprise_EnterpriseId" FOREIGN KEY ("EnterpriseId") REFERENCES tbl_enterprise (id) ON DELETE CASCADE
);

CREATE TABLE document_approvals (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DocumentId" integer NOT NULL,
    "SubmittedByUserId" integer NOT NULL,
    "DecidedByUserId" integer NULL,
    "Decision" integer NOT NULL,
    "RejectionReason" text NULL,
    "SubmittedAt" timestamp without time zone NOT NULL,
    "DecidedAt" timestamp without time zone NULL,
    CONSTRAINT "PK_document_approvals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_document_approvals_tbl_app_user_DecidedByUserId" FOREIGN KEY ("DecidedByUserId") REFERENCES tbl_app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_document_approvals_tbl_app_user_SubmittedByUserId" FOREIGN KEY ("SubmittedByUserId") REFERENCES tbl_app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_document_approvals_tbl_document_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES tbl_document (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_approval_configs_EnterpriseId" ON approval_configs ("EnterpriseId");

CREATE INDEX "IX_document_approvals_DecidedByUserId" ON document_approvals ("DecidedByUserId");

CREATE INDEX "IX_document_approvals_Decision" ON document_approvals ("Decision");

CREATE INDEX "IX_document_approvals_DocumentId" ON document_approvals ("DocumentId");

CREATE INDEX "IX_document_approvals_SubmittedByUserId" ON document_approvals ("SubmittedByUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430173740_AddApprovalWorkflow', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE tbl_pricing_grid (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CounterPartId" integer NOT NULL,
    "MerchandiseId" integer NULL,
    "DiscountRate" double precision NOT NULL,
    "ValidFrom" timestamp without time zone NULL,
    "ValidUntil" timestamp without time zone NULL,
    "IsActive" boolean NOT NULL,
    "Notes" text NULL,
    "CreationDate" timestamp without time zone NULL,
    "UpdateDate" timestamp without time zone NULL,
    "UpdatedById" integer NOT NULL,
    CONSTRAINT "PK_tbl_pricing_grid" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_pricing_grid_tbl_app_user_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES tbl_app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_pricing_grid_tbl_counter_part_CounterPartId" FOREIGN KEY ("CounterPartId") REFERENCES tbl_counter_part (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_pricing_grid_tbl_merchandise_MerchandiseId" FOREIGN KEY ("MerchandiseId") REFERENCES tbl_merchandise (id) ON DELETE SET NULL
);

CREATE INDEX "IX_tbl_pricing_grid_CounterPartId_MerchandiseId_IsActive" ON tbl_pricing_grid ("CounterPartId", "MerchandiseId", "IsActive");

CREATE INDEX "IX_tbl_pricing_grid_MerchandiseId" ON tbl_pricing_grid ("MerchandiseId");

CREATE INDEX "IX_tbl_pricing_grid_UpdatedById" ON tbl_pricing_grid ("UpdatedById");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501081326_AddPricingGrid', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_document_merchandise ALTER COLUMN merchandiseid DROP NOT NULL;

ALTER TABLE tbl_document_merchandise ADD description text NULL;

ALTER TABLE tbl_document_merchandise ADD line_type integer NOT NULL DEFAULT 1;

ALTER TABLE tbl_document_merchandise ADD transporterid integer NULL;

CREATE INDEX "IX_tbl_document_merchandise_transporterid" ON tbl_document_merchandise (transporterid);

ALTER TABLE tbl_document_merchandise ADD CONSTRAINT "FK_tbl_document_merchandise_tbl_transporter_transporterid" FOREIGN KEY (transporterid) REFERENCES tbl_transporter (id) ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260502062652_AddTransportFees', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_payments ADD "Currency" text NULL;

ALTER TABLE tbl_payments ADD "ExchangeRate" numeric NOT NULL DEFAULT 1.0;

ALTER TABLE tbl_document ADD "Currency" text NULL;

ALTER TABLE tbl_document ADD "ExchangeRate" double precision NOT NULL DEFAULT 1.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260504084657_AddMultiCurrencySupport', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_person ADD basesalary numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_person ADD overtimehours numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_payments ALTER COLUMN "ExchangeRate" SET DEFAULT 1.0;

ALTER TABLE tbl_document ALTER COLUMN "ExchangeRate" SET DEFAULT 1.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505064255_AddHRFieldsToPerson', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_employee_payslips ALTER COLUMN netsalary TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ALTER COLUMN deductions TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ALTER COLUMN bonuses TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ALTER COLUMN basesalary TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ADD brutsalary numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_employee_payslips ADD cnssamount numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_employee_payslips ADD irppamount numeric(18,3) NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505064358_UpdatePayslipFields', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_employee_payslips ADD cssamount numeric(18,3) NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505064421_AddCssAmountToPayslip', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_app_user ADD "PasswordResetToken" text NULL;

ALTER TABLE tbl_app_user ADD "PasswordResetTokenExpiry" timestamp without time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510132144_AddPasswordResetTokenToAppUser', '7.0.20');

COMMIT;



-- ==========================================
-- APPENDED CUSTOM NON-EF MIGRATIONS
-- ==========================================


-- From script.sql
-- History table
CREATE TABLE tbl_quantity_mouvement_history (
    id SERIAL PRIMARY KEY,
    original_movement_id INTEGER NOT NULL,
    documentid INTEGER NOT NULL,
    merchandiseid INTEGER NOT NULL,
    lengthids TEXT,
    quantity DECIMAL(10,4),
    archiveddate TIMESTAMP NOT NULL,
    FOREIGN KEY (merchandiseid) REFERENCES tbl_merchandise(id) ON DELETE CASCADE
);

-- Length details history
CREATE TABLE tbl_list_of_lengths_history (
    id SERIAL PRIMARY KEY,
    historyid INTEGER NOT NULL,
    lengthappvarid INTEGER,
    numberofpieces INTEGER,
    quantity DECIMAL(10,4),
    FOREIGN KEY (historyid) REFERENCES tbl_quantity_mouvements(id) ON DELETE CASCADE,
    FOREIGN KEY (lengthappvarid) REFERENCES tbl_appvariable(id) ON DELETE SET NULL
);

-- Indexes for better performance
CREATE INDEX idx_quantity_history_merchandise ON tbl_quantity_mouvement_history(merchandiseid);
CREATE INDEX idx_quantity_history_original ON tbl_quantity_mouvement_history(original_movement_id);
CREATE INDEX idx_length_history_parent ON tbl_list_of_lengths_history(historyid);

-- From script.sql
-- Consolidated Migration for Employee Management Features
-- Includes: Leave Management, Payslips, and Advance Management

-- 1. Leave Management
CREATE TABLE IF NOT EXISTS tbl_employee_leaves (
    id SERIAL PRIMARY KEY,
    employeeid INTEGER NOT NULL REFERENCES tbl_person(id) ON DELETE CASCADE,
    leavetype VARCHAR(100) NOT NULL,
    startdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    enddate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    durationdays NUMERIC(5, 2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    createdat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    updatedat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc')
);

-- 2. Payslip Management
CREATE TABLE IF NOT EXISTS tbl_employee_payslips (
    id SERIAL PRIMARY KEY,
    employeeid INTEGER NOT NULL REFERENCES tbl_person(id) ON DELETE CASCADE,
    periodmonth INTEGER NOT NULL,
    periodyear INTEGER NOT NULL,
    basesalary NUMERIC(19, 4) NOT NULL DEFAULT 0,
    bonuses NUMERIC(19, 4) DEFAULT 0,
    deductions NUMERIC(19, 4) DEFAULT 0,
    netsalary NUMERIC(19, 4) NOT NULL DEFAULT 0,
    generatedat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc')
);

-- 3. Advance Management
CREATE TABLE IF NOT EXISTS tbl_employee_advances (
    id SERIAL PRIMARY KEY,
    employeeid INTEGER NOT NULL REFERENCES tbl_person(id) ON DELETE CASCADE,
    amount NUMERIC(19, 4) NOT NULL DEFAULT 0,
    requestdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    repaymentschedule TEXT,
    amountrepaid NUMERIC(19, 4) DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    createdat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    updatedat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_employee_leaves_employee ON tbl_employee_leaves(employeeid);
CREATE INDEX IF NOT EXISTS idx_employee_payslips_employee ON tbl_employee_payslips(employeeid);
CREATE INDEX IF NOT EXISTS idx_employee_advances_employee ON tbl_employee_advances(employeeid);


-- From add_payment_instrument.sql
-- Table des instruments de paiement (traites, chèques à échéances)
CREATE TABLE IF NOT EXISTS tbl_payment_instrument (
    id              SERIAL PRIMARY KEY,
    paymentid       INTEGER NOT NULL REFERENCES tbl_payments(id) ON DELETE CASCADE,
    type            VARCHAR(20) NOT NULL DEFAULT 'TRAITE',
    instrumentnumber VARCHAR(100),
    bank            VARCHAR(200),
    owner           VARCHAR(200),
    porter          VARCHAR(200),
    issuedate       TIMESTAMP,
    duedate         TIMESTAMP,        -- ★ Date d'échéance
    expirationdate  TIMESTAMP,
    banksettlementstatus VARCHAR(30) DEFAULT 'PENDING',
    paidatbankdate  TIMESTAMP,
    ispaidatbank    BOOLEAN NOT NULL DEFAULT FALSE,
    notes           TEXT,
    createdat       TIMESTAMP DEFAULT NOW(),
    createdby       VARCHAR(255),
    updatedat       TIMESTAMP,
    updatedbyid     INTEGER
);

-- Index sur la date d'échéance pour les requêtes de timeline
CREATE INDEX IF NOT EXISTS idx_payment_instrument_duedate ON tbl_payment_instrument(duedate);
CREATE INDEX IF NOT EXISTS idx_payment_instrument_paymentid ON tbl_payment_instrument(paymentid);

-- Add auditretentionmonths column to tbl_enterprise table with default value of 12
ALTER TABLE tbl_enterprise ADD COLUMN auditretentionmonths integer DEFAULT 12;

-- Add documentnumberingconfig column to tbl_enterprise table
ALTER TABLE tbl_enterprise ADD COLUMN documentnumberingconfig text;

-- Add minimumstock column to tbl_stock table with default value of 0
ALTER TABLE tbl_stock ADD COLUMN minimumstock numeric(19,4) DEFAULT 0;

-- Add reference column to tbl_holding_tax table
ALTER TABLE tbl_holding_tax ADD COLUMN reference text;

-- Add total_credit_notes column to tbl_document table with default value of 0
ALTER TABLE tbl_document ADD COLUMN total_credit_notes numeric(19,4) DEFAULT 0;


-- From V0.15__bank_fees_and_cash.sql
-- Phase 1: Gestion des Versements en Banque & Caisses

-- 1. Mise à jour de la table Banks pour les coûts d'opérations et solde initial
ALTER TABLE "tbl_bank"
  ADD COLUMN IF NOT EXISTS "ChequeDepositFeeHT"  NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "TraiteDepositFeeHT"   NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "WireTransferFeeHT"    NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "MiscFeeHT"            NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "InitialBalance"        NUMERIC(14,3) DEFAULT 0;

-- 2. Table BankDeposits (versements effectués en banque)
CREATE TABLE IF NOT EXISTS "tbl_bank_deposits" (
  "id"               SERIAL PRIMARY KEY,
  "BankId"           INT NOT NULL REFERENCES "tbl_bank"("id"),
  "DepositDate"      TIMESTAMP NOT NULL DEFAULT NOW(),
  "DepositType"      VARCHAR(20) NOT NULL,  -- ESPECE | CHEQUE | TRAITE | VIREMENT
  "AmountHT"         NUMERIC(14,3) NOT NULL,
  "FeeHT"            NUMERIC(10,3) NOT NULL DEFAULT 0,
  "TaxRate"          NUMERIC(5,3)  NOT NULL DEFAULT 0, -- Lu depuis AppVariable (TVA)
  "FeeWithTax"       NUMERIC(10,3) NOT NULL DEFAULT 0, -- FeeHT * (1 + TaxRate/100)
  "NetAmount"        NUMERIC(14,3) NOT NULL,           -- AmountHT - FeeWithTax (Montant réellement crédité)
  "Reference"        VARCHAR(100),
  "Notes"            VARCHAR(500),
  "PaymentInstrumentId" INT REFERENCES "tbl_payment_instrument"("id"), -- Lien vers chèque/traite si applicable
  "SalesSiteId"      INT REFERENCES "tbl_sales_sites"("id"), -- Caisse source (pour versement espèces)
  "CreatedByUserId"  INT REFERENCES "tbl_app_user"("id"),
  "CreatedAt"        TIMESTAMP NOT NULL DEFAULT NOW(),
  "IsDeleted"        BOOLEAN NOT NULL DEFAULT FALSE
);

-- 3. Table CaisseMovements (flux de trésorerie par point de vente)
CREATE TABLE IF NOT EXISTS "tbl_caisse_movements" (
  "id"               SERIAL PRIMARY KEY,
  "SalesSiteId"      INT NOT NULL REFERENCES "tbl_sales_sites"("id"),
  "MovementDate"     TIMESTAMP NOT NULL DEFAULT NOW(),
  "Type"             VARCHAR(20) NOT NULL,   -- ENTREE | SORTIE
  "Reason"           VARCHAR(50) NOT NULL,   -- ENCAISSEMENT | VERSEMENT_BANQUE | DEPENSE | INIT | RECTIFICATION
  "Amount"           NUMERIC(14,3) NOT NULL,
  "Reference"        VARCHAR(100),
  "Notes"            VARCHAR(500),
  "BankDepositId"    INT REFERENCES "tbl_bank_deposits"("id"), -- Si sortie liée à un versement
  "PaymentId"        INT REFERENCES "tbl_payments"("id"), -- Lien vers le paiement (Vente)
  "CreatedByUserId"  INT REFERENCES "tbl_app_user"("id"),
  "CreatedAt"        TIMESTAMP NOT NULL DEFAULT NOW(),
  "IsDeleted"        BOOLEAN NOT NULL DEFAULT FALSE
);

-- Index pour la performance
CREATE INDEX IF NOT EXISTS "idx_bankdeposits_bankid" ON "tbl_bank_deposits"("BankId");
CREATE INDEX IF NOT EXISTS "idx_caissemovements_sitid" ON "tbl_caisse_movements"("SalesSiteId");


-- From V0.19__add_user_permissions.sql
-- Create the UserPermissions table.
-- Stores a JSONB permissions blob per AppUser.
-- One row per user; null = no explicit grants (defaults apply).
CREATE TABLE IF NOT EXISTS "tbl_user_permissions" (
    "Id"          SERIAL PRIMARY KEY,
    "UserId"      INTEGER NOT NULL UNIQUE,
    "Permissions" JSONB   NOT NULL DEFAULT '{}',
    "UpdatedAt"   TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_userperm_user FOREIGN KEY ("UserId") REFERENCES "tbl_app_user"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_userperm_userid ON "tbl_user_permissions" ("UserId");


-- From 01_Create_BankTransaction.sql
-- Create the BankTransaction table.
-- Stores bank transactions for rapprochement bancaire.
CREATE TABLE IF NOT EXISTS "tbl_bank_transaction" (
    "Id"              SERIAL PRIMARY KEY,
    "BankId"          INTEGER NOT NULL,
    "TransactionDate" TIMESTAMP NOT NULL,
    "Description"     TEXT NULL,
    "Debit"           NUMERIC(18, 3) NOT NULL,
    "Credit"          NUMERIC(18, 3) NOT NULL,
    "Reference"       VARCHAR(100) NULL,
    "IsReconciled"    BOOLEAN NOT NULL DEFAULT FALSE,
    "CreationDate"    TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdateDate"      TIMESTAMP NOT NULL DEFAULT NOW(),
    "IsDeleted"       BOOLEAN NULL DEFAULT FALSE,
    "UpdatedBy"       INTEGER NULL,
    CONSTRAINT fk_bank_transaction_bank FOREIGN KEY ("BankId") REFERENCES "tbl_bank"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bank_transaction_bankid ON "tbl_bank_transaction" ("BankId");



-- ==========================================
-- APPENDED CUSTOM NON-EF MIGRATIONS
-- ==========================================


-- From script.sql
-- History table
CREATE TABLE tbl_quantity_mouvement_history (
    id SERIAL PRIMARY KEY,
    original_movement_id INTEGER NOT NULL,
    documentid INTEGER NOT NULL,
    merchandiseid INTEGER NOT NULL,
    lengthids TEXT,
    quantity DECIMAL(10,4),
    archiveddate TIMESTAMP NOT NULL,
    FOREIGN KEY (merchandiseid) REFERENCES tbl_merchandise(id) ON DELETE CASCADE
);

-- Length details history
CREATE TABLE tbl_list_of_lengths_history (
    id SERIAL PRIMARY KEY,
    historyid INTEGER NOT NULL,
    lengthappvarid INTEGER,
    numberofpieces INTEGER,
    quantity DECIMAL(10,4),
    FOREIGN KEY (historyid) REFERENCES tbl_quantity_mouvements(id) ON DELETE CASCADE,
    FOREIGN KEY (lengthappvarid) REFERENCES tbl_appvariable(id) ON DELETE SET NULL
);

-- Indexes for better performance
CREATE INDEX idx_quantity_history_merchandise ON tbl_quantity_mouvement_history(merchandiseid);
CREATE INDEX idx_quantity_history_original ON tbl_quantity_mouvement_history(original_movement_id);
CREATE INDEX idx_length_history_parent ON tbl_list_of_lengths_history(historyid);

-- From script.sql
-- Consolidated Migration for Employee Management Features
-- Includes: Leave Management, Payslips, and Advance Management

-- 1. Leave Management
CREATE TABLE IF NOT EXISTS tbl_employee_leaves (
    id SERIAL PRIMARY KEY,
    employeeid INTEGER NOT NULL REFERENCES tbl_person(id) ON DELETE CASCADE,
    leavetype VARCHAR(100) NOT NULL,
    startdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    enddate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    durationdays NUMERIC(5, 2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    createdat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    updatedat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc')
);

-- 2. Payslip Management
CREATE TABLE IF NOT EXISTS tbl_employee_payslips (
    id SERIAL PRIMARY KEY,
    employeeid INTEGER NOT NULL REFERENCES tbl_person(id) ON DELETE CASCADE,
    periodmonth INTEGER NOT NULL,
    periodyear INTEGER NOT NULL,
    basesalary NUMERIC(19, 4) NOT NULL DEFAULT 0,
    bonuses NUMERIC(19, 4) DEFAULT 0,
    deductions NUMERIC(19, 4) DEFAULT 0,
    netsalary NUMERIC(19, 4) NOT NULL DEFAULT 0,
    generatedat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc')
);

-- 3. Advance Management
CREATE TABLE IF NOT EXISTS tbl_employee_advances (
    id SERIAL PRIMARY KEY,
    employeeid INTEGER NOT NULL REFERENCES tbl_person(id) ON DELETE CASCADE,
    amount NUMERIC(19, 4) NOT NULL DEFAULT 0,
    requestdate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    repaymentschedule TEXT,
    amountrepaid NUMERIC(19, 4) DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    createdat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    updatedat TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_employee_leaves_employee ON tbl_employee_leaves(employeeid);
CREATE INDEX IF NOT EXISTS idx_employee_payslips_employee ON tbl_employee_payslips(employeeid);
CREATE INDEX IF NOT EXISTS idx_employee_advances_employee ON tbl_employee_advances(employeeid);


-- From add_payment_instrument.sql
-- Table des instruments de paiement (traites, chèques à échéances)
CREATE TABLE IF NOT EXISTS tbl_payment_instrument (
    id              SERIAL PRIMARY KEY,
    paymentid       INTEGER NOT NULL REFERENCES tbl_payments(id) ON DELETE CASCADE,
    type            VARCHAR(20) NOT NULL DEFAULT 'TRAITE',
    instrumentnumber VARCHAR(100),
    bank            VARCHAR(200),
    owner           VARCHAR(200),
    porter          VARCHAR(200),
    issuedate       TIMESTAMP,
    duedate         TIMESTAMP,        -- ★ Date d'échéance
    expirationdate  TIMESTAMP,
    banksettlementstatus VARCHAR(30) DEFAULT 'PENDING',
    paidatbankdate  TIMESTAMP,
    ispaidatbank    BOOLEAN NOT NULL DEFAULT FALSE,
    notes           TEXT,
    createdat       TIMESTAMP DEFAULT NOW(),
    createdby       VARCHAR(255),
    updatedat       TIMESTAMP,
    updatedbyid     INTEGER
);

-- Index sur la date d'échéance pour les requêtes de timeline
CREATE INDEX IF NOT EXISTS idx_payment_instrument_duedate ON tbl_payment_instrument(duedate);
CREATE INDEX IF NOT EXISTS idx_payment_instrument_paymentid ON tbl_payment_instrument(paymentid);

-- Add auditretentionmonths column to tbl_enterprise table with default value of 12
ALTER TABLE tbl_enterprise ADD COLUMN auditretentionmonths integer DEFAULT 12;

-- Add documentnumberingconfig column to tbl_enterprise table
ALTER TABLE tbl_enterprise ADD COLUMN documentnumberingconfig text;

-- Add minimumstock column to tbl_stock table with default value of 0
ALTER TABLE tbl_stock ADD COLUMN minimumstock numeric(19,4) DEFAULT 0;

-- Add reference column to tbl_holding_tax table
ALTER TABLE tbl_holding_tax ADD COLUMN reference text;

-- Add total_credit_notes column to tbl_document table with default value of 0
ALTER TABLE tbl_document ADD COLUMN total_credit_notes numeric(19,4) DEFAULT 0;


-- From V0.15__bank_fees_and_cash.sql
-- Phase 1: Gestion des Versements en Banque & Caisses

-- 1. Mise à jour de la table Banks pour les coûts d'opérations et solde initial
ALTER TABLE "tbl_bank"
  ADD COLUMN IF NOT EXISTS "ChequeDepositFeeHT"  NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "TraiteDepositFeeHT"   NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "WireTransferFeeHT"    NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "MiscFeeHT"            NUMERIC(10,3) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "InitialBalance"        NUMERIC(14,3) DEFAULT 0;

-- 2. Table BankDeposits (versements effectués en banque)
CREATE TABLE IF NOT EXISTS "tbl_bank_deposits" (
  "id"               SERIAL PRIMARY KEY,
  "BankId"           INT NOT NULL REFERENCES "tbl_bank"("id"),
  "DepositDate"      TIMESTAMP NOT NULL DEFAULT NOW(),
  "DepositType"      VARCHAR(20) NOT NULL,  -- ESPECE | CHEQUE | TRAITE | VIREMENT
  "AmountHT"         NUMERIC(14,3) NOT NULL,
  "FeeHT"            NUMERIC(10,3) NOT NULL DEFAULT 0,
  "TaxRate"          NUMERIC(5,3)  NOT NULL DEFAULT 0, -- Lu depuis AppVariable (TVA)
  "FeeWithTax"       NUMERIC(10,3) NOT NULL DEFAULT 0, -- FeeHT * (1 + TaxRate/100)
  "NetAmount"        NUMERIC(14,3) NOT NULL,           -- AmountHT - FeeWithTax (Montant réellement crédité)
  "Reference"        VARCHAR(100),
  "Notes"            VARCHAR(500),
  "PaymentInstrumentId" INT REFERENCES "tbl_payment_instrument"("id"), -- Lien vers chèque/traite si applicable
  "SalesSiteId"      INT REFERENCES "tbl_sales_sites"("id"), -- Caisse source (pour versement espèces)
  "CreatedByUserId"  INT REFERENCES "tbl_app_user"("id"),
  "CreatedAt"        TIMESTAMP NOT NULL DEFAULT NOW(),
  "IsDeleted"        BOOLEAN NOT NULL DEFAULT FALSE
);

-- 3. Table CaisseMovements (flux de trésorerie par point de vente)
CREATE TABLE IF NOT EXISTS "tbl_caisse_movements" (
  "id"               SERIAL PRIMARY KEY,
  "SalesSiteId"      INT NOT NULL REFERENCES "tbl_sales_sites"("id"),
  "MovementDate"     TIMESTAMP NOT NULL DEFAULT NOW(),
  "Type"             VARCHAR(20) NOT NULL,   -- ENTREE | SORTIE
  "Reason"           VARCHAR(50) NOT NULL,   -- ENCAISSEMENT | VERSEMENT_BANQUE | DEPENSE | INIT | RECTIFICATION
  "Amount"           NUMERIC(14,3) NOT NULL,
  "Reference"        VARCHAR(100),
  "Notes"            VARCHAR(500),
  "BankDepositId"    INT REFERENCES "tbl_bank_deposits"("id"), -- Si sortie liée à un versement
  "PaymentId"        INT REFERENCES "tbl_payments"("id"), -- Lien vers le paiement (Vente)
  "CreatedByUserId"  INT REFERENCES "tbl_app_user"("id"),
  "CreatedAt"        TIMESTAMP NOT NULL DEFAULT NOW(),
  "IsDeleted"        BOOLEAN NOT NULL DEFAULT FALSE
);

-- Index pour la performance
CREATE INDEX IF NOT EXISTS "idx_bankdeposits_bankid" ON "tbl_bank_deposits"("BankId");
CREATE INDEX IF NOT EXISTS "idx_caissemovements_sitid" ON "tbl_caisse_movements"("SalesSiteId");


-- From V0.19__add_user_permissions.sql
-- Create the UserPermissions table.
-- Stores a JSONB permissions blob per AppUser.
-- One row per user; null = no explicit grants (defaults apply).
CREATE TABLE IF NOT EXISTS "tbl_user_permissions" (
    "Id"          SERIAL PRIMARY KEY,
    "UserId"      INTEGER NOT NULL UNIQUE,
    "Permissions" JSONB   NOT NULL DEFAULT '{}',
    "UpdatedAt"   TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_userperm_user FOREIGN KEY ("UserId") REFERENCES "tbl_app_user"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_userperm_userid ON "tbl_user_permissions" ("UserId");


-- From 01_Create_BankTransaction.sql
-- Create the BankTransaction table.
-- Stores bank transactions for rapprochement bancaire.
CREATE TABLE IF NOT EXISTS "tbl_bank_transaction" (
    "Id"              SERIAL PRIMARY KEY,
    "BankId"          INTEGER NOT NULL,
    "TransactionDate" TIMESTAMP NOT NULL,
    "Description"     TEXT NULL,
    "Debit"           NUMERIC(18, 3) NOT NULL,
    "Credit"          NUMERIC(18, 3) NOT NULL,
    "Reference"       VARCHAR(100) NULL,
    "IsReconciled"    BOOLEAN NOT NULL DEFAULT FALSE,
    "CreationDate"    TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdateDate"      TIMESTAMP NOT NULL DEFAULT NOW(),
    "IsDeleted"       BOOLEAN NULL DEFAULT FALSE,
    "UpdatedBy"       INTEGER NULL,
    CONSTRAINT fk_bank_transaction_bank FOREIGN KEY ("BankId") REFERENCES "tbl_bank"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bank_transaction_bankid ON "tbl_bank_transaction" ("BankId");

