import { Component, Inject, OnInit, inject } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { ToastrService } from 'ngx-toastr';
import { DocumentService } from '../../../../services/components/document.service';
import { CounterpartService } from '../../../../services/components/counterpart.service';
import { CounterPart } from '../../../../models/components/counterpart';
import { CounterPartType_FR } from '../../../../shared/constants/list_of_constants';
import { Document, DocumentTypes, DocStatus, BillingStatus } from '../../../../models/components/document';
import { AuthenticationService } from '../../../../services/components/authentication.service';
import { AppVariableService } from '../../../../services/configuration/app-variable.service';
import { AppVariable } from '../../../../models/configuration/appvariable';

@Component({
  selector: 'app-add-credit-note-dialog',
  templateUrl: './add-credit-note-dialog.component.html',
  styleUrl: './add-credit-note-dialog.component.css'
})
export class AddCreditNoteDialogComponent implements OnInit {
  form!: FormGroup;
  loading = false;
  
  suppliers: CounterPart[] = [];
  invoices: Document[] = [];
  tvas: AppVariable[] = [];
  
  user = inject(AuthenticationService).getUserDetail();

  constructor(
    private fb: FormBuilder,
    private docService: DocumentService,
    private counterpartService: CounterpartService,
    private appVarService: AppVariableService,
    private toastr: ToastrService,
    private dialogRef: MatDialogRef<AddCreditNoteDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: { type: 'supplier' | 'customer' }
  ) {
    this.createForm();
  }

  ngOnInit(): void {
    this.loadSuppliers();
    this.loadTVAs();
    
    // Listen to supplier changes to load their invoices
    this.form.get('counterpart')?.valueChanges.subscribe(supplier => {
      if (supplier) {
        this.loadInvoices(supplier.id);
      } else {
        this.invoices = [];
      }
    });

    // Auto-calculate TTC
    this.form.valueChanges.subscribe(() => {
      this.calculateTotals();
    });
  }

  createForm() {
    this.form = this.fb.group({
      counterpart: [null, Validators.required],
      parentInvoice: [null],
      description: ['', Validators.required],
      amountHT: [0, [Validators.required, Validators.min(0.001)]],
      tva: [null, Validators.required],
      amountTTC: [{ value: 0, disabled: true }]
    });
  }

  loadSuppliers() {
    const type = this.data.type === 'supplier' ? CounterPartType_FR.supplier : CounterPartType_FR.customer;
    this.counterpartService.GetAll(type).subscribe(res => {
      this.suppliers = res;
    });
  }

  loadTVAs() {
    this.appVarService.GetAll('TVA').subscribe(res => {
      this.tvas = res;
      // Set default TVA if available (e.g. 19%)
      const defaultTva = res.find(t => t.value === '19' || t.value === '19%');
      if (defaultTva) this.form.get('tva')?.setValue(defaultTva);
    });
  }

  loadInvoices(supplierId: number) {
    const docType = this.data.type === 'supplier' ? DocumentTypes.supplierInvoice : DocumentTypes.customerInvoice;
    this.docService.GetByType(docType).subscribe(res => {
      this.invoices = res.filter(d => d.counterpart?.id === supplierId);
    });
  }

  calculateTotals() {
    const ht = this.form.get('amountHT')?.value || 0;
    const tvaVar = this.form.get('tva')?.value;
    let tvaRate = 0;
    
    if (tvaVar) {
      tvaRate = parseFloat(tvaVar.value.replace('%', '')) / 100;
    }
    
    const ttc = ht * (1 + tvaRate);
    this.form.get('amountTTC')?.setValue(ttc, { emitEvent: false });
  }

  onSubmit() {
    if (this.form.invalid) return;

    this.loading = true;
    const formValue = this.form.getRawValue();
    const parentInvoice = formValue.parentInvoice as Document;

    const creditNote: any = {
      id: 0,
      type: this.data.type === 'supplier' ? DocumentTypes.supplierInvoiceReturn : DocumentTypes.customerInvoiceReturn,
      docnumber: '', // Will be generated by backend
      description: formValue.description,
      isinvoiced: true,
      isservice: true, // Mark as financial (no stock)
      counterpart: formValue.counterpart,
      total_ht_net_doc: formValue.amountHT,
      total_tva_doc: formValue.amountTTC - formValue.amountHT,
      total_net_ttc: formValue.amountTTC,
      total_net_payable: formValue.amountTTC,
      updatedbyid: this.user?.id ? +this.user.id : 0,
      creationdate: new Date(),
      updatedate: new Date(),
      docstatus: DocStatus.Created,
      billingstatus: BillingStatus.NotBilled,
      isdeleted: false
    };

    if (parentInvoice) {
      this.docService.CreateCreditNote(parentInvoice.id, creditNote).subscribe({
        next: () => {
          this.toastr.success('Avoir créé avec succès');
          this.dialogRef.close(true);
          this.loading = false;
        },
        error: (err) => {
          console.error(err);
          this.toastr.error('Erreur lors de la création de l\'avoir');
          this.loading = false;
        }
      });
    } else {
      // Manual creation without parent invoice link (if allowed)
      this.docService.Add(creditNote).subscribe({
        next: () => {
          this.toastr.success('Avoir créé avec succès');
          this.dialogRef.close(true);
          this.loading = false;
        },
        error: (err) => {
          console.error(err);
          this.toastr.error('Erreur lors de la création de l\'avoir');
          this.loading = false;
        }
      });
    }
  }

  onCancel() {
    this.dialogRef.close();
  }
}
