

                ALTER TABLE tbl_document_merchandise 
                DROP COLUMN IF EXISTS quantitydelivered;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260414201428_AddQuantityDeliveredToDocumentMerchandise', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE "HoldingTax" DROP CONSTRAINT "FK_HoldingTax_tbl_app_user_AppUsersId";

ALTER TABLE "HoldingTax" DROP CONSTRAINT "PK_HoldingTax";

ALTER TABLE "HoldingTax" RENAME TO tbl_holding_tax;

ALTER TABLE tbl_holding_tax RENAME COLUMN "isSigned" TO issigned;

ALTER TABLE tbl_holding_tax RENAME COLUMN "UpdatedById" TO updatedbyid;

ALTER TABLE tbl_holding_tax RENAME COLUMN "UpdateDate" TO updatedate;

ALTER TABLE tbl_holding_tax RENAME COLUMN "TaxValue" TO taxvalue;

ALTER TABLE tbl_holding_tax RENAME COLUMN "TaxPercentage" TO taxpercentage;

ALTER TABLE tbl_holding_tax RENAME COLUMN "NewAmountDocValue" TO newamountdocvalue;

ALTER TABLE tbl_holding_tax RENAME COLUMN "IsDeleted" TO isdeleted;

ALTER TABLE tbl_holding_tax RENAME COLUMN "Description" TO description;

ALTER TABLE tbl_holding_tax RENAME COLUMN "CreationDate" TO creationdate;

ALTER TABLE tbl_holding_tax RENAME COLUMN "AppUsersId" TO appusersid;

ALTER TABLE tbl_holding_tax RENAME COLUMN "Id" TO id;

ALTER INDEX "IX_HoldingTax_AppUsersId" RENAME TO "IX_tbl_holding_tax_appusersid";

ALTER TABLE tbl_document_merchandise ALTER COLUMN "QuantityDelivered" SET DEFAULT 0.0;

ALTER TABLE tbl_holding_tax ALTER COLUMN isdeleted SET DEFAULT FALSE;

ALTER TABLE tbl_holding_tax ADD reference text NULL;

ALTER TABLE tbl_holding_tax ADD CONSTRAINT "PK_tbl_holding_tax" PRIMARY KEY (id);

ALTER TABLE tbl_holding_tax ADD CONSTRAINT "FK_tbl_holding_tax_tbl_app_user_appusersid" FOREIGN KEY (appusersid) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260415131429_FixHoldingTaxMappingFinal', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE tbl_purchase_price_history (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    idarticle integer NOT NULL,
    idcounterpart integer NOT NULL,
    pricevalue double precision NOT NULL,
    transactiondate timestamp without time zone NOT NULL,
    iddocument integer NOT NULL,
    docnumber character varying(50) NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    CONSTRAINT "PK_tbl_purchase_price_history" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_purchase_price_history_tbl_article_idarticle" FOREIGN KEY (idarticle) REFERENCES tbl_article (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_purchase_price_history_tbl_counter_part_idcounterpart" FOREIGN KEY (idcounterpart) REFERENCES tbl_counter_part (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_purchase_price_history_tbl_document_iddocument" FOREIGN KEY (iddocument) REFERENCES tbl_document (id) ON DELETE RESTRICT
);

CREATE TABLE tbl_sales_price_history (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    idarticle integer NOT NULL,
    idcounterpart integer NOT NULL,
    pricevalue double precision NOT NULL,
    transactiondate timestamp without time zone NOT NULL,
    iddocument integer NOT NULL,
    docnumber character varying(50) NULL,
    creationdate timestamp without time zone NULL,
    updatedate timestamp without time zone NULL,
    isdeleted boolean NOT NULL,
    CONSTRAINT "PK_tbl_sales_price_history" PRIMARY KEY (id),
    CONSTRAINT "FK_tbl_sales_price_history_tbl_article_idarticle" FOREIGN KEY (idarticle) REFERENCES tbl_article (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_sales_price_history_tbl_counter_part_idcounterpart" FOREIGN KEY (idcounterpart) REFERENCES tbl_counter_part (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_sales_price_history_tbl_document_iddocument" FOREIGN KEY (iddocument) REFERENCES tbl_document (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_tbl_purchase_price_history_idarticle" ON tbl_purchase_price_history (idarticle);

CREATE INDEX "IX_tbl_purchase_price_history_idcounterpart" ON tbl_purchase_price_history (idcounterpart);

CREATE INDEX "IX_tbl_purchase_price_history_iddocument" ON tbl_purchase_price_history (iddocument);

CREATE INDEX "IX_tbl_sales_price_history_idarticle" ON tbl_sales_price_history (idarticle);

CREATE INDEX "IX_tbl_sales_price_history_idcounterpart" ON tbl_sales_price_history (idcounterpart);

CREATE INDEX "IX_tbl_sales_price_history_iddocument" ON tbl_sales_price_history (iddocument);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419151900_AddTransactionalPriceHistory', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_sales_price_history ADD idupdatedby integer NULL;

ALTER TABLE tbl_purchase_price_history ADD idupdatedby integer NULL;

CREATE INDEX "IX_tbl_sell_history_idappuser" ON tbl_sell_history (idappuser);

CREATE INDEX "IX_tbl_sales_price_history_idupdatedby" ON tbl_sales_price_history (idupdatedby);

CREATE INDEX "IX_tbl_purchase_price_history_idupdatedby" ON tbl_purchase_price_history (idupdatedby);

ALTER TABLE tbl_purchase_price_history ADD CONSTRAINT "FK_tbl_purchase_price_history_tbl_app_user_idupdatedby" FOREIGN KEY (idupdatedby) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

ALTER TABLE tbl_sales_price_history ADD CONSTRAINT "FK_tbl_sales_price_history_tbl_app_user_idupdatedby" FOREIGN KEY (idupdatedby) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

ALTER TABLE tbl_sell_history ADD CONSTRAINT "FK_tbl_sell_history_tbl_app_user_idappuser" FOREIGN KEY (idappuser) REFERENCES tbl_app_user (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420085615_AddUserAuditToHistory', '7.0.20');

COMMIT;

START TRANSACTION;


                UPDATE tbl_account_ledger
                SET credit = debit, debit = 0
                WHERE type = 'supplierReceipt' 
                  AND (debit > 0 OR debit < 0)
                  AND credit = 0;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429052233_FixSupplierLedgerValues', '7.0.20');

COMMIT;

START TRANSACTION;


                UPDATE tbl_appvariable av
                SET value = sub.calculated_balance
                FROM (
                    SELECT cp.id, (COALESCE(cp.openingbalance, 0) + COALESCE(SUM(al.credit), 0) - COALESCE(SUM(al.debit), 0)) as calculated_balance
                    FROM tbl_counter_part cp
                    LEFT JOIN tbl_account_ledger al ON cp.id = al.counterpartid
                    WHERE cp.type IN (2, 3)
                    GROUP BY cp.id, cp.openingbalance
                ) sub
                WHERE av.nature = 'supplierBalance' 
                  AND (split_part(av.name, '|', 1))::int = sub.id;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429052415_RefreshSupplierBalances', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE tbl_pricing_grid (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CounterPartId" integer NOT NULL,
    "MerchandiseId" integer NULL,
    "DiscountRate" double precision NOT NULL,
    "ValidFrom" timestamp without time zone NULL,
    "ValidUntil" timestamp without time zone NULL,
    "IsActive" boolean NOT NULL,
    "Notes" text NULL,
    "CreationDate" timestamp without time zone NULL,
    "UpdateDate" timestamp without time zone NULL,
    "UpdatedById" integer NOT NULL,
    CONSTRAINT "PK_tbl_pricing_grid" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_pricing_grid_tbl_app_user_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES tbl_app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_tbl_pricing_grid_tbl_counter_part_CounterPartId" FOREIGN KEY ("CounterPartId") REFERENCES tbl_counter_part (id) ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_pricing_grid_tbl_merchandise_MerchandiseId" FOREIGN KEY ("MerchandiseId") REFERENCES tbl_merchandise (id) ON DELETE SET NULL
);

CREATE INDEX "IX_tbl_pricing_grid_CounterPartId_MerchandiseId_IsActive" ON tbl_pricing_grid ("CounterPartId", "MerchandiseId", "IsActive");

CREATE INDEX "IX_tbl_pricing_grid_MerchandiseId" ON tbl_pricing_grid ("MerchandiseId");

CREATE INDEX "IX_tbl_pricing_grid_UpdatedById" ON tbl_pricing_grid ("UpdatedById");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501081326_AddPricingGrid', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_document_merchandise ALTER COLUMN merchandiseid DROP NOT NULL;

ALTER TABLE tbl_document_merchandise ADD description text NULL;

ALTER TABLE tbl_document_merchandise ADD line_type integer NOT NULL DEFAULT 1;

ALTER TABLE tbl_document_merchandise ADD transporterid integer NULL;

CREATE INDEX "IX_tbl_document_merchandise_transporterid" ON tbl_document_merchandise (transporterid);

ALTER TABLE tbl_document_merchandise ADD CONSTRAINT "FK_tbl_document_merchandise_tbl_transporter_transporterid" FOREIGN KEY (transporterid) REFERENCES tbl_transporter (id) ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260502062652_AddTransportFees', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_payments ADD "Currency" text NULL;

ALTER TABLE tbl_payments ADD "ExchangeRate" numeric NOT NULL DEFAULT 1.0;

ALTER TABLE tbl_document ADD "Currency" text NULL;

ALTER TABLE tbl_document ADD "ExchangeRate" double precision NOT NULL DEFAULT 1.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260504084657_AddMultiCurrencySupport', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_person ADD basesalary numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_person ADD overtimehours numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_payments ALTER COLUMN "ExchangeRate" SET DEFAULT 1.0;

ALTER TABLE tbl_document ALTER COLUMN "ExchangeRate" SET DEFAULT 1.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505064255_AddHRFieldsToPerson', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_employee_payslips ALTER COLUMN netsalary TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ALTER COLUMN deductions TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ALTER COLUMN bonuses TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ALTER COLUMN basesalary TYPE numeric(18,3);

ALTER TABLE tbl_employee_payslips ADD brutsalary numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_employee_payslips ADD cnssamount numeric(18,3) NOT NULL DEFAULT 0.0;

ALTER TABLE tbl_employee_payslips ADD irppamount numeric(18,3) NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505064358_UpdatePayslipFields', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_employee_payslips ADD cssamount numeric(18,3) NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260505064421_AddCssAmountToPayslip', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_app_user ADD "PasswordResetToken" text NULL;

ALTER TABLE tbl_app_user ADD "PasswordResetTokenExpiry" timestamp without time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260510132144_AddPasswordResetTokenToAppUser', '7.0.20');

COMMIT;

