-- NO SCHEMA CHANGES REQUIRED FOR V0.11
-- The relationship between tbl_holding_tax and tbl_document is already established via the holdingtaxid column.
-- Updated EF Core configuration to support bidirectional navigation without structural DB modifications.
