START TRANSACTION;

-- Cleanup: Drop incorrect duplicate columns if they exist
ALTER TABLE tbl_enterprise DROP COLUMN IF EXISTS "AuditRetentionMonths";
ALTER TABLE tbl_enterprise DROP COLUMN IF EXISTS "AuditRentetionMonths";

-- Add numbering and audit columns to enterprise table (safely)
ALTER TABLE tbl_enterprise ADD COLUMN IF NOT EXISTS documentnumberingconfig text NULL;
ALTER TABLE tbl_enterprise ADD COLUMN IF NOT EXISTS auditretentionmonths integer NOT NULL DEFAULT 12;

-- Create AuditLogs table for §5.20 — Audit Trail complet
CREATE TABLE IF NOT EXISTS "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NULL,
    "UserName" text NULL,
    "Action" text NOT NULL,
    "TableName" text NOT NULL,
    "Timestamp" timestamp without time zone NOT NULL,
    "KeyValues" text NULL,
    "OldValues" text NULL,
    "NewValues" text NULL,
    "ChangedColumns" text NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

-- Register migration in history
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260413070039_AddAuditTrail', '7.0.20'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413070039_AddAuditTrail'
);

-- §5.7 — Alerte de stock bas
ALTER TABLE tbl_stock ADD COLUMN IF NOT EXISTS minimumstock double precision NOT NULL DEFAULT 0;

COMMIT;
