import { TraitePixelMap } from '@/types/traite-calibration';

/**
 * Scanned Template Dimensions (Source of Truth for Visual Geometry)
 */
export const TEMPLATE_WIDTH_PX = 820;
export const TEMPLATE_HEIGHT_PX = 536;
export const TEMPLATE_ASPECT_RATIO = TEMPLATE_WIDTH_PX / TEMPLATE_HEIGHT_PX; // ~1.52985

/**
 * Baseline initial estimates for the 19 dynamic fields on the 820x536 scanned template.
 * These are visual baseline starting points meant to be fine-tuned interactively in the Calibration Inspector.
 */
export const INITIAL_TRAITE_PIXEL_MAP: TraitePixelMap = {
  signatureTire: {
    templateX: 18,
    templateY: 180,
    templateWidth: 155,
    templateHeight: 50,
    label: '1. Signature du tiré',
    sampleValue: '[Cachet & Signature Tiré]',
    category: 'corps',
  },
  echeance: {
    templateX: 200,
    templateY: 28,
    templateWidth: 160,
    templateHeight: 22,
    label: '2. Échéance',
    sampleValue: '31/12/2026',
    category: 'corps',
  },
  ribTire: {
    templateX: 260,
    templateY: 110,
    templateWidth: 290,
    templateHeight: 22,
    label: '3. RIB/RIP du tiré (Corps)',
    sampleValue: '08 001 1234567890123 45',
    category: 'corps',
  },
  ordrePaiement: {
    templateX: 200,
    templateY: 162,
    templateWidth: 350,
    templateHeight: 24,
    label: '4. Ordre de paiement / bénéficiaire',
    sampleValue: 'SOCIETE SOCOFEB SARL',
    category: 'corps',
  },
  montant: {
    templateX: 580,
    templateY: 58,
    templateWidth: 200,
    templateHeight: 24,
    label: '5. Montant',
    sampleValue: '# 12 345,678 TND #',
    category: 'corps',
  },
  montantLettres: {
    templateX: 28,
    templateY: 236,
    templateWidth: 740,
    templateHeight: 26,
    label: '6. Montant en lettres',
    sampleValue: '# DOUZE MILLE TROIS CENT QUARANTE-CINQ DINARS ET 678 MILLIMES #',
    category: 'corps',
  },
  tireur: {
    templateX: 28,
    templateY: 162,
    templateWidth: 160,
    templateHeight: 24,
    label: '7. Tireur',
    sampleValue: 'ACYA ENTERPRISE',
    category: 'corps',
  },
  lieuCreation: {
    templateX: 400,
    templateY: 28,
    templateWidth: 110,
    templateHeight: 20,
    label: '8. Lieu de création',
    sampleValue: 'Tunis',
    category: 'corps',
  },
  dateCreation: {
    templateX: 400,
    templateY: 62,
    templateWidth: 110,
    templateHeight: 20,
    label: '9. Date de création',
    sampleValue: '11/08/2026',
    category: 'corps',
  },
  nomCedant: {
    templateX: 440,
    templateY: 290,
    templateWidth: 330,
    templateHeight: 22,
    label: '10. Nom du cédant',
    sampleValue: 'SOCIETE SOCOFEB SARL',
    category: 'talon',
  },
  ribTireTalon: {
    templateX: 40,
    templateY: 348,
    templateWidth: 280,
    templateHeight: 22,
    label: '11. RIB/RIP du tiré (Talon)',
    sampleValue: '08 001 1234567890123 45',
    category: 'talon',
  },
  codeEtablissement: {
    templateX: 28,
    templateY: 405,
    templateWidth: 38,
    templateHeight: 22,
    label: '12. Code établissement',
    sampleValue: '08',
    category: 'talon',
  },
  codeAgence: {
    templateX: 72,
    templateY: 405,
    templateWidth: 52,
    templateHeight: 22,
    label: '13. Code agence',
    sampleValue: '001',
    category: 'talon',
  },
  numCompte: {
    templateX: 130,
    templateY: 405,
    templateWidth: 168,
    templateHeight: 22,
    label: '14. N° de compte',
    sampleValue: '1234567890123',
    category: 'talon',
  },
  cle: {
    templateX: 304,
    templateY: 405,
    templateWidth: 28,
    templateHeight: 22,
    label: '15. Clé',
    sampleValue: '45',
    category: 'talon',
  },
  valeurEn: {
    templateX: 330,
    templateY: 348,
    templateWidth: 100,
    templateHeight: 30,
    label: '16. Valeur en',
    sampleValue: 'TND 12 345,678',
    category: 'talon',
  },
  nomAdresseTire: {
    templateX: 345,
    templateY: 405,
    templateWidth: 425,
    templateHeight: 46,
    label: '17. Nom et adresse du tiré',
    sampleValue: 'ACYA STE - Zone Industrielle Charguia, Tunis',
    category: 'talon',
  },
  domiciliation: {
    templateX: 450,
    templateY: 348,
    templateWidth: 320,
    templateHeight: 35,
    label: '18. Domiciliation',
    sampleValue: 'BIAT - Agence Avenue Habib Bourguiba, Tunis',
    category: 'talon',
  },
  signatureTireur: {
    templateX: 600,
    templateY: 455,
    templateWidth: 185,
    templateHeight: 52,
    label: '19. Signature du tireur',
    sampleValue: '[Signature Tireur]',
    category: 'talon',
  },
};
