export const BANKS_TN = [
    { key: 'CITIBANK', value: 'CITIBANK (BRANCHE OFF-SHORE)', logo: '' },
    { key: 'TIB', value: 'TUNIS INTERNATIONAL BANK', logo: '' },
    { key: 'TFB', value: 'TUNISIAN FOREIGN BANK', logo: '' },
    { key: 'NAIB', value: 'NORTH AFRICA INTERNATIONAL BANK', logo: '' },
    { key: 'WIB', value: 'WIFAK INTERNATIONAL BANK', logo: '' },
    { key: 'AL BARAKA', value: 'AL BARAKA BANK TUNISIA', logo: '' },
    { key: 'BZ', value: 'BANQUE ZITOUNA', logo: '' },
    { key: 'BFPME', value: 'BANQUE DE FINANCEMENT DES PETITES ET MOYENNES ENTREPRISES', logo: '' },
    { key: 'BTL', value: 'BANQUE TUNISO-LIBYENNE', logo: '' },
    { key: 'BTE', value: 'BANQUE DE TUNISIE & DES EMIRATS', logo: '' },
    { key: 'QNB', value: 'QATAR NATIONAL BANK - TUNIS', logo: '' },
    { key: 'TSB', value: 'TUNISIAN SAOUDI BANK', logo: '' },
    { key: 'BTK', value: 'BANQUE TUNISO-KOWEITIENNE', logo: '' },
    { key: 'ABC', value: 'ARAB BANKING CORPORATION - TUNISIA', logo: '' },
    { key: 'CITI', value: 'CITIBANK (Branche ON - SHORE)', logo: '' },
    { key: 'BH', value: 'BANQUE DE L\'HABITAT', logo: '' },
    { key: 'UIB', value: 'UNION INTERNATIONALE DE BANQUES', logo: '' },
    { key: 'UBCI', value: 'UNION BANCAIRE POUR LE COMMERCE ET L\'INDUSTRIE', logo: '' },
    { key: 'STB', value: 'SOCIETE TUNISIENNE DE BANQUE', logo: '' },
    { key: 'BIAT', value: 'BANQUE INTERNATIONALE ARABE DE TUNISIE', logo: '' },
    { key: 'AB', value: 'AMEN BANK', logo: '' },
    { key: 'BTS', value: 'BANQUE TUNISIENNE DE SOLIDARITE', logo: '' },
    { key: 'BT', value: 'BANQUE DE TUNISIE', logo: '' },
    { key: 'ATTIJ', value: 'BANQUE ATTIJARI DE TUNISIE', logo: '' },
    { key: 'BNA', value: 'BANQUE NATIONALE AGRICOLE', logo: '' },
    { key: 'ATB', value: 'ARAB TUNISIAN BANK', logo: '' },
    { key: 'BCT', value: 'BANQUE CENTRALE DE TUNIS', logo: '' }
];
