using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ms.webapp.api.acya.infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAuditTrail : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "auditretentionmonths",
                table: "tbl_enterprise",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "AuditLogs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserId = table.Column<int>(type: "integer", nullable: true),
                    UserName = table.Column<string>(type: "text", nullable: true),
                    Action = table.Column<string>(type: "text", nullable: false),
                    TableName = table.Column<string>(type: "text", nullable: false),
                    Timestamp = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    KeyValues = table.Column<string>(type: "text", nullable: true),
                    OldValues = table.Column<string>(type: "text", nullable: true),
                    NewValues = table.Column<string>(type: "text", nullable: true),
                    ChangedColumns = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AuditLogs", x => x.Id);
                });

            migrationBuilder.Sql(@"
                ALTER TABLE tbl_enterprise ADD COLUMN IF NOT EXISTS documentnumberingconfig text;

                CREATE TABLE IF NOT EXISTS tbl_employee_advances (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    employeeid integer NOT NULL,
                    amount numeric NOT NULL,
                    requestdate timestamp without time zone NOT NULL,
                    repaymentschedule text NULL,
                    amountrepaid numeric NOT NULL,
                    status text NOT NULL,
                    createdat timestamp without time zone NULL,
                    updatedat timestamp without time zone NULL,
                    CONSTRAINT ""PK_tbl_employee_advances"" PRIMARY KEY (id),
                    CONSTRAINT ""FK_tbl_employee_advances_tbl_person_employeeid"" FOREIGN KEY (employeeid) REFERENCES tbl_person (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_tbl_employee_advances_employeeid"" ON tbl_employee_advances (employeeid);

                CREATE TABLE IF NOT EXISTS tbl_employee_leaves (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    employeeid integer NOT NULL,
                    leavetype text NOT NULL,
                    startdate timestamp without time zone NOT NULL,
                    enddate timestamp without time zone NOT NULL,
                    durationdays numeric NOT NULL,
                    status text NOT NULL,
                    createdat timestamp without time zone NULL,
                    updatedat timestamp without time zone NULL,
                    CONSTRAINT ""PK_tbl_employee_leaves"" PRIMARY KEY (id),
                    CONSTRAINT ""FK_tbl_employee_leaves_tbl_person_employeeid"" FOREIGN KEY (employeeid) REFERENCES tbl_person (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_tbl_employee_leaves_employeeid"" ON tbl_employee_leaves (employeeid);

                CREATE TABLE IF NOT EXISTS tbl_employee_payslips (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    employeeid integer NOT NULL,
                    periodmonth integer NOT NULL,
                    periodyear integer NOT NULL,
                    basesalary numeric NOT NULL,
                    bonuses numeric NOT NULL,
                    deductions numeric NOT NULL,
                    netsalary numeric NOT NULL,
                    generatedat timestamp without time zone NULL,
                    CONSTRAINT ""PK_tbl_employee_payslips"" PRIMARY KEY (id),
                    CONSTRAINT ""FK_tbl_employee_payslips_tbl_person_employeeid"" FOREIGN KEY (employeeid) REFERENCES tbl_person (id) ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_tbl_employee_payslips_employeeid"" ON tbl_employee_payslips (employeeid);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AuditLogs");

            /*
            migrationBuilder.DropTable(
                name: "tbl_employee_advances");

            migrationBuilder.DropTable(
                name: "tbl_employee_leaves");

            migrationBuilder.DropTable(
                name: "tbl_employee_payslips");
            */

            migrationBuilder.DropColumn(
                name: "auditretentionmonths",
                table: "tbl_enterprise");

            migrationBuilder.Sql(@"
                ALTER TABLE tbl_enterprise DROP COLUMN IF EXISTS documentnumberingconfig;
            ");
        }
    }
}
