// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ms.webapp.api.acya.infrastructure;

#nullable disable

namespace ms.webapp.api.acya.infrastructure.Migrations
{
    [DbContext(typeof(WoodAppContext))]
    partial class WoodAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentMerchandise", b =>
                {
                    b.Property<int>("DocumentsId")
                        .HasColumnType("integer");

                    b.Property<int>("MerchandisesId")
                        .HasColumnType("integer");

                    b.HasKey("DocumentsId", "MerchandisesId");

                    b.HasIndex("MerchandisesId");

                    b.ToTable("DocumentMerchandise");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int?>("EnterpriseId")
                        .HasColumnType("integer")
                        .HasColumnName("enterpriseid");

                    b.Property<int>("IdPerson")
                        .HasColumnType("integer")
                        .HasColumnName("idperson");

                    b.Property<int?>("IdSalesSite")
                        .HasColumnType("integer")
                        .HasColumnName("idsalessite");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea")
                        .HasColumnName("passwordhash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea")
                        .HasColumnName("passwordsalt");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId")
                        .IsUnique();

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdSalesSite")
                        .IsUnique();

                    b.ToTable("tbl_app_user", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.AppVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nature")
                        .HasColumnType("text")
                        .HasColumnName("nature");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<bool?>("isActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool?>("isDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("isdefault");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool?>("isEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("iseditable");

                    b.HasKey("Id");

                    b.ToTable("tbl_appvariable", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency")
                        .HasColumnType("text")
                        .HasColumnName("agency");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Designation")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("Rib")
                        .HasColumnType("text")
                        .HasColumnName("rib");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_bank", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.FirstChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdParent")
                        .HasColumnType("integer")
                        .HasColumnName("idparent");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.HasKey("Id");

                    b.HasIndex("IdParent");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_first_child", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tbl_parent", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.SecondChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdFirstChild")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("IdFirstChild");

                    b.ToTable("tbl_second_child", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.CounterPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("bankaccountnumber");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bankname");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Gouvernorate")
                        .HasColumnType("text")
                        .HasColumnName("gouvernorate");

                    b.Property<Guid?>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("IdentityCardNumber")
                        .HasColumnType("text")
                        .HasColumnName("identitycardnumber");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("jobtitle");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<double?>("MaximumDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("maximumdiscount");

                    b.Property<double?>("MaximumSalesBar")
                        .HasColumnType("double precision")
                        .HasColumnName("maximumsalesbar");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PatenteCode")
                        .HasColumnType("text")
                        .HasColumnName("patentecode");

                    b.Property<string>("PhoneNumberOne")
                        .HasColumnType("text")
                        .HasColumnName("phonenumberone");

                    b.Property<string>("PhoneNumberTwo")
                        .HasColumnType("text")
                        .HasColumnName("phonenumbertwo");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("taxregistrationnumber");

                    b.Property<int?>("TransporterId")
                        .HasColumnType("integer")
                        .HasColumnName("transporterid");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_counter_part", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CounterPartId")
                        .HasColumnType("integer")
                        .HasColumnName("counterpartid");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocNumber")
                        .HasColumnType("text")
                        .HasColumnName("docnumber");

                    b.Property<int>("DocStatus")
                        .HasColumnType("integer")
                        .HasColumnName("docstatus");

                    b.Property<int?>("HoldingTaxId")
                        .HasColumnType("integer")
                        .HasColumnName("holdingtaxid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsInvoiced")
                        .HasColumnType("boolean")
                        .HasColumnName("isinvoiced");

                    b.Property<int>("SalesSiteId")
                        .HasColumnType("integer")
                        .HasColumnName("salessiteid");

                    b.Property<int?>("StockTransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("stocktransactiontype");

                    b.Property<string>("SupplierReference")
                        .HasColumnType("text")
                        .HasColumnName("supplierreference");

                    b.Property<int?>("TaxeId")
                        .HasColumnType("integer")
                        .HasColumnName("taxeid");

                    b.Property<double>("TotalCostDiscountDoc")
                        .HasColumnType("double precision")
                        .HasColumnName("totalcostdiscount");

                    b.Property<double>("TotalCostHTNetDoc")
                        .HasColumnType("double precision")
                        .HasColumnName("totalcostpriceht");

                    b.Property<double>("TotalCostNetTTCDoc")
                        .HasColumnType("double precision")
                        .HasColumnName("totalcostpricettc");

                    b.Property<double>("TotalCostTvaDoc")
                        .HasColumnType("double precision")
                        .HasColumnName("totalcosttva");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updatedbyid");

                    b.Property<bool>("WithHoldingTax")
                        .HasColumnType("boolean")
                        .HasColumnName("withholdingtax");

                    b.HasKey("Id");

                    b.HasIndex("CounterPartId");

                    b.HasIndex("HoldingTaxId");

                    b.HasIndex("SalesSiteId");

                    b.HasIndex("TaxeId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_document", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.DocumentDocumentRelationship", b =>
                {
                    b.Property<int>("ParentDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_document_id");

                    b.Property<int>("ChildDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("child_document_id");

                    b.HasKey("ParentDocumentId", "ChildDocumentId");

                    b.HasIndex("ChildDocumentId");

                    b.ToTable("tbl_document_document_relationship", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.DocumentMerchandise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CostDiscountValue")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_discount_value");

                    b.Property<double>("CostHT")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_ht");

                    b.Property<double>("CostNetHT")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_net_ht");

                    b.Property<double>("CostTTC")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_ttc");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("discount_percentage");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("documentid");

                    b.Property<int>("MerchandiseId")
                        .HasColumnType("integer")
                        .HasColumnName("merchandiseid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<double>("TvaValue")
                        .HasColumnType("double precision")
                        .HasColumnName("tva_value");

                    b.Property<double>("UnitPriceHT")
                        .HasColumnType("double precision")
                        .HasColumnName("unitprice_ht");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MerchandiseId");

                    b.ToTable("tbl_document_merchandise", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Capital")
                        .HasColumnType("text")
                        .HasColumnName("capital");

                    b.Property<string>("CommercialRegister")
                        .HasColumnType("text")
                        .HasColumnName("commercialregister");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Devise")
                        .HasColumnType("text")
                        .HasColumnName("devise");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("enterpriseguid");

                    b.Property<bool?>("IsSalingWood")
                        .HasColumnType("boolean")
                        .HasColumnName("issalingwood");

                    b.Property<string>("MatriculeFiscal")
                        .HasColumnType("text")
                        .HasColumnName("matriculefiscal");

                    b.Property<string>("MobileOne")
                        .HasColumnType("text")
                        .HasColumnName("mobileone");

                    b.Property<string>("MobileTwo")
                        .HasColumnType("text")
                        .HasColumnName("mobiletwo");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameResponsable")
                        .HasColumnType("text")
                        .HasColumnName("nameresponsable");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PositionResponsable")
                        .HasColumnType("text")
                        .HasColumnName("positionresponsable");

                    b.Property<string>("SiegeAddress")
                        .HasColumnType("text")
                        .HasColumnName("siegeaddress");

                    b.Property<string>("SurnameResponsable")
                        .HasColumnType("text")
                        .HasColumnName("surnameresponsable");

                    b.HasKey("Id");

                    b.ToTable("tbl_enterprise", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.HoldingTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUsersId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("NewAmountDocValue")
                        .HasColumnType("double precision");

                    b.Property<double>("TaxPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("TaxValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<bool>("isSigned")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AppUsersId");

                    b.ToTable("HoldingTax");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Merchandise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowNegativStock")
                        .HasColumnType("boolean")
                        .HasColumnName("allownegativstock");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("articleid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdMergedMerchandise")
                        .HasColumnType("integer")
                        .HasColumnName("idmergedmerchandise");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsInvoicible")
                        .HasColumnType("boolean")
                        .HasColumnName("isinvoicible");

                    b.Property<bool>("IsMergedWith")
                        .HasColumnType("boolean")
                        .HasColumnName("ismergedwith");

                    b.Property<string>("PackageReference")
                        .HasColumnType("text")
                        .HasColumnName("packagereference");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updatedbyid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_merchandise", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.PendingNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TargetGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("targetgroup");

                    b.HasKey("Id");

                    b.HasIndex("TargetGroup", "Status");

                    b.ToTable("tbl_pending_notification", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text")
                        .HasColumnName("bankaccount");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bankname");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthdate");

                    b.Property<string>("BirthTown")
                        .HasColumnType("text")
                        .HasColumnName("birthtown");

                    b.Property<string>("Cin")
                        .HasColumnType("text")
                        .HasColumnName("cin");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<DateTime?>("FireDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("firedate");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hiredate");

                    b.Property<string>("IdCnss")
                        .HasColumnType("text")
                        .HasColumnName("idcnss");

                    b.Property<bool>("IsAppUser")
                        .HasColumnType("boolean")
                        .HasColumnName("isappuser");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("idrole");

                    b.Property<int?>("UpdadatedById")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.HasKey("Id");

                    b.ToTable("tbl_person", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FirstChildId")
                        .HasColumnType("integer")
                        .HasColumnName("idsubcategory");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsWood")
                        .HasColumnType("boolean")
                        .HasColumnName("iswood");

                    b.Property<double>("LastPurchasePriceTTC")
                        .HasColumnType("double precision")
                        .HasColumnName("lastpurchaseprice_ttc");

                    b.Property<string>("Lengths")
                        .HasColumnType("text")
                        .HasColumnName("lengths");

                    b.Property<double?>("MinQuantity")
                        .HasColumnType("double precision")
                        .HasColumnName("minquantity");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("idcategory");

                    b.Property<double?>("ProfitMarginPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("profitmarginpercentage");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<int?>("SellHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("idsellhistory");

                    b.Property<double?>("SellPriceHT")
                        .HasColumnType("double precision")
                        .HasColumnName("sellprice_ht");

                    b.Property<double?>("SellPriceTTC")
                        .HasColumnType("double precision")
                        .HasColumnName("sellprice_ttc");

                    b.Property<int?>("ThicknessId")
                        .HasColumnType("integer")
                        .HasColumnName("idthickness");

                    b.Property<int>("TvaId")
                        .HasColumnType("integer")
                        .HasColumnName("idtva");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.Property<int?>("WidthId")
                        .HasColumnType("integer")
                        .HasColumnName("idwidth");

                    b.HasKey("Id");

                    b.HasIndex("FirstChildId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SellHistoryId");

                    b.HasIndex("ThicknessId");

                    b.HasIndex("TvaId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("WidthId");

                    b.ToTable("tbl_article", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.ListOfLength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppVarLengthId")
                        .HasColumnType("integer")
                        .HasColumnName("lengthappvarid");

                    b.Property<int>("NumberOfPieces")
                        .HasColumnType("integer")
                        .HasColumnName("numberofpieces");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<int>("QuantityMovementId")
                        .HasColumnType("integer")
                        .HasColumnName("quantitymouvementid");

                    b.HasKey("Id");

                    b.HasIndex("AppVarLengthId");

                    b.HasIndex("QuantityMovementId");

                    b.ToTable("tbl_list_of_lengths", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.QuantityMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<int>("DocumentMerchandiseId")
                        .HasColumnType("integer")
                        .HasColumnName("document_merchandise_id");

                    b.Property<string>("LengthIds")
                        .HasColumnType("text")
                        .HasColumnName("lengthids");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.HasKey("Id");

                    b.HasIndex("DocumentMerchandiseId")
                        .IsUnique();

                    b.ToTable("tbl_quantity_mouvements", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.SellPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("idarticle");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<double>("PriceValue")
                        .HasColumnType("double precision")
                        .HasColumnName("pricevalue");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.HasKey("Id");

                    b.ToTable("tbl_sell_history", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text")
                        .HasColumnName("bankaccountnumber");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bankname");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumberOne")
                        .HasColumnType("text")
                        .HasColumnName("phonenumberone");

                    b.Property<string>("PhoneNumberTwo")
                        .HasColumnType("text")
                        .HasColumnName("phonenumbertwo");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<string>("RepresentedByFullname")
                        .HasColumnType("text")
                        .HasColumnName("representedbyfullname");

                    b.Property<string>("RepresentedByName")
                        .HasColumnType("text")
                        .HasColumnName("representedbyname");

                    b.Property<string>("RepresentedBySurname")
                        .HasColumnType("text")
                        .HasColumnName("representedbysurname");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasColumnType("text")
                        .HasColumnName("taxregistrationnumber");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("idappuser");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_provider", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.SalesSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CodePost")
                        .HasColumnType("text")
                        .HasColumnName("codepost");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("integer")
                        .HasColumnName("enterpriseid");

                    b.Property<string>("Gouvernorate")
                        .HasColumnType("text")
                        .HasColumnName("gouvernorate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("boolean")
                        .HasColumnName("isforsale");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("tbl_sales_sites", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate");

                    b.Property<int>("MerchandiseId")
                        .HasColumnType("integer")
                        .HasColumnName("idmerchandise");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SalesSiteId")
                        .HasColumnType("integer")
                        .HasColumnName("idsite");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updatedbyid");

                    b.HasKey("Id");

                    b.HasIndex("MerchandiseId");

                    b.HasIndex("SalesSiteId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_stock", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.StockTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmationdate");

                    b.Property<int?>("ConfirmedById")
                        .HasColumnType("integer")
                        .HasColumnName("confirmedbyid");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ExitDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("exitdocumentid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ReceiptDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("receiptdocumentid");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejectionreason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transferdate");

                    b.Property<int?>("TransporterId")
                        .HasColumnType("integer")
                        .HasColumnName("transporterid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ExitDocumentId");

                    b.HasIndex("ReceiptDocumentId");

                    b.HasIndex("Reference")
                        .HasDatabaseName("ix_tbl_stock_transfer_reference")
                        .HasFilter("reference IS NOT NULL");

                    b.HasIndex("TransferDate")
                        .HasDatabaseName("ix_tbl_stock_transfer_transferdate");

                    b.HasIndex("TransporterId");

                    b.ToTable("tbl_stock_transfer", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Transporter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicleid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("tbl_transporter", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Draining")
                        .HasColumnType("text")
                        .HasColumnName("draining");

                    b.Property<DateTime?>("DrainingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("drainingdate");

                    b.Property<DateTime?>("InsuranceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insurancedate");

                    b.Property<string>("Mileage")
                        .HasColumnType("text")
                        .HasColumnName("mileage");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serialnumber");

                    b.Property<DateTime?>("TechnicalVisitDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("technicalvisitdate");

                    b.HasKey("Id");

                    b.ToTable("tbl_vehicle", (string)null);
                });

            modelBuilder.Entity("ms.webapp.api.acya.infrastructure.AppHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Iscr")
                        .HasColumnType("boolean")
                        .HasColumnName("iscr");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("tbl_app_health", (string)null);
                });

            modelBuilder.Entity("DocumentMerchandise", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Merchandise", null)
                        .WithMany()
                        .HasForeignKey("MerchandisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.AppUser", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Enterprise", "Enterprise")
                        .WithOne()
                        .HasForeignKey("ms.webapp.api.acya.core.Entities.AppUser", "EnterpriseId");

                    b.HasOne("ms.webapp.api.acya.core.Entities.Person", "Persons")
                        .WithMany()
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.SalesSite", "SalesSite")
                        .WithOne()
                        .HasForeignKey("ms.webapp.api.acya.core.Entities.AppUser", "IdSalesSite");

                    b.Navigation("Enterprise");

                    b.Navigation("Persons");

                    b.Navigation("SalesSite");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Bank", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.FirstChild", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Categories.Parent", "Parents")
                        .WithMany("FirstChildren")
                        .HasForeignKey("IdParent");

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.Parent", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.SecondChild", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.HasOne("ms.webapp.api.acya.core.Entities.Categories.FirstChild", "FirstChildren")
                        .WithMany("SecondChildren")
                        .HasForeignKey("IdFirstChild");

                    b.Navigation("AppUser");

                    b.Navigation("FirstChildren");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.CounterPart", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Transporter", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tbl_counter_part_tbl_transporter");

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUsers")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUsers");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Document", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.CounterPart", "CounterPart")
                        .WithMany()
                        .HasForeignKey("CounterPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.HoldingTax", "HoldingTaxes")
                        .WithMany()
                        .HasForeignKey("HoldingTaxId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tbl_document_tbl_holding_tax");

                    b.HasOne("ms.webapp.api.acya.core.Entities.SalesSite", "SalesSite")
                        .WithMany()
                        .HasForeignKey("SalesSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppVariable", "Taxes")
                        .WithMany()
                        .HasForeignKey("TaxeId");

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUsers")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tbl_document_tbl_app_user");

                    b.Navigation("AppUsers");

                    b.Navigation("CounterPart");

                    b.Navigation("HoldingTaxes");

                    b.Navigation("SalesSite");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.DocumentDocumentRelationship", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Document", "ChildDocument")
                        .WithMany()
                        .HasForeignKey("ChildDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Document", "ParentDocument")
                        .WithMany("ChildDocuments")
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildDocument");

                    b.Navigation("ParentDocument");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.DocumentMerchandise", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Document", "Document")
                        .WithMany("DocumentMerchandises")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Merchandise", "Merchandise")
                        .WithMany("DocumentMerchandises")
                        .HasForeignKey("MerchandiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Merchandise");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.HoldingTax", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUsers")
                        .WithMany()
                        .HasForeignKey("AppUsersId");

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Merchandise", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Product.Article", "Articles")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUsers")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUsers");

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.Article", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Categories.FirstChild", "FirstChildren")
                        .WithMany()
                        .HasForeignKey("FirstChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Categories.Parent", "Parents")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Product.SellPriceHistory", "SellHistories")
                        .WithMany()
                        .HasForeignKey("SellHistoryId");

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppVariable", "Thicknesses")
                        .WithMany()
                        .HasForeignKey("ThicknessId");

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppVariable", "TVAs")
                        .WithMany()
                        .HasForeignKey("TvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUsers")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppVariable", "Widths")
                        .WithMany()
                        .HasForeignKey("WidthId");

                    b.Navigation("AppUsers");

                    b.Navigation("FirstChildren");

                    b.Navigation("Parents");

                    b.Navigation("SellHistories");

                    b.Navigation("TVAs");

                    b.Navigation("Thicknesses");

                    b.Navigation("Widths");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.ListOfLength", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.AppVariable", "AppVarLength")
                        .WithMany()
                        .HasForeignKey("AppVarLengthId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ms.webapp.api.acya.core.Entities.Product.QuantityMovement", "QuantityMovements")
                        .WithMany("ListOfLengths")
                        .HasForeignKey("QuantityMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppVarLength");

                    b.Navigation("QuantityMovements");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.QuantityMovement", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.DocumentMerchandise", "DocumentMerchandise")
                        .WithOne("QuantityMovements")
                        .HasForeignKey("ms.webapp.api.acya.core.Entities.Product.QuantityMovement", "DocumentMerchandiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentMerchandise");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Provider", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUsers")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.SalesSite", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Enterprise", "Enterprise")
                        .WithMany("Sites")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Stock", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Merchandise", "Merchandises")
                        .WithMany()
                        .HasForeignKey("MerchandiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.SalesSite", "SalesSites")
                        .WithMany()
                        .HasForeignKey("SalesSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "AppUsers")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_stock_tbl_app_user");

                    b.Navigation("AppUsers");

                    b.Navigation("Merchandises");

                    b.Navigation("SalesSites");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.StockTransfer", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Document", "ExitDocument")
                        .WithMany()
                        .HasForeignKey("ExitDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Document", "ReceiptDocument")
                        .WithMany()
                        .HasForeignKey("ReceiptDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ms.webapp.api.acya.core.Entities.Transporter", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("ExitDocument");

                    b.Navigation("ReceiptDocument");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Transporter", b =>
                {
                    b.HasOne("ms.webapp.api.acya.core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tbl_transporter_tbl_vehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.FirstChild", b =>
                {
                    b.Navigation("SecondChildren");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Categories.Parent", b =>
                {
                    b.Navigation("FirstChildren");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Document", b =>
                {
                    b.Navigation("ChildDocuments");

                    b.Navigation("DocumentMerchandises");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.DocumentMerchandise", b =>
                {
                    b.Navigation("QuantityMovements");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Enterprise", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Merchandise", b =>
                {
                    b.Navigation("DocumentMerchandises");
                });

            modelBuilder.Entity("ms.webapp.api.acya.core.Entities.Product.QuantityMovement", b =>
                {
                    b.Navigation("ListOfLengths");
                });
#pragma warning restore 612, 618
        }
    }
}
